const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(file,mocks={}){const module={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>{if(n in mocks)return mocks[n];throw Error('Missing mock '+n);},module,module.exports);return module.exports;}
const presentation=load('lib/asset-history-presentation.ts'),theme=load('lib/report-theme.ts'),print=load('lib/report-print.ts',{'./report-theme.ts':theme});
const usage=load('lib/asset-usage.ts');
const asset={id:'asset',title:'2022 New Holland TT4.90',yearModel:2022,hours:1300,kind:'tractor',condition:'good',serialNumber:'TEST-SERIAL',specsJson:{}};
const event={id:'event',action:'Asset details updated',actorName:'Example Workshop',source:'Leads',category:'details',createdAt:'2026-10-04T10:00:00Z',before:{hours:1276},after:{hours:1300}};
function setup(list){let rendered='';const report=load('lib/asset-history-report.ts',{'./maintenance-report-style':load('lib/maintenance-report-style.ts'),'next/server':{NextResponse:Response},'./asset-history':{listUnifiedAssetHistory:list},'./asset-history-presentation':presentation,'./report-print':print,'./report-pdf':{renderReportHtmlToPdf:async html=>{rendered=html;return Buffer.from('%PDF-test');}},'./report-pdf-request':{normaliseReportPdfFileName:s=>s+'.pdf'},'./asset-registers':{getAssetRegisterReportLogoUrl:async()=>''},'./report-logo':{resolveReportLogoUrlForHtml:async()=>''},'./asset-usage':usage});return {report,html:()=>rendered};}
test('history attachment paginates all permitted history and applies search to older entries',async()=>{const calls=[];const {report,html}=setup(async(owner,id,options)=>{calls.push(options);return options.before?{items:[event],nextBefore:null}:{items:[{...event,id:'first',actorName:'Someone else'}],nextBefore:'cursor'};});const request={url:'https://example.test/api/history?format=pdf&search=Workshop',nextUrl:new URL('https://example.test/api/history?format=pdf&search=Workshop'),headers:new Headers()};const options={owner:false,actorId:'recipient',categories:['details'],detailFields:['hours'],category:'details'};const response=await report.assetHistoryPdfResponse(request,'owner',asset,options);assert.equal(response.headers.get('content-type'),'application/pdf');assert.equal(response.headers.get('cache-control'),'no-store, private');assert.equal(calls.length,2);assert.deepEqual(calls[1].detailFields,['hours']);assert.equal(calls[1].owner,false);assert.equal(calls[1].before,'cursor');assert.ok(html().includes('Example Workshop'));assert.ok(!html().includes('Someone else'));assert.ok(!html().includes('TEST-SERIAL'));assert.ok(!html().includes('Year Model:'));assert.match(html(),/1\s276/);});
test('history uses the canonical report shell, escapes content and supports an empty report',()=>{const {report}=setup();const html=report.buildAssetHistoryReportHtml(asset,[{...event,actorName:'<script>unsafe</script>'}],{owner:true},'', '',new Date('2026-10-05T10:00:00Z'));assert.ok(html.includes('Asset History Report'));assert.ok(html.includes('assetReportHeader'));assert.ok(html.includes('Powered by Aim4price.com'));assert.ok(html.includes('TEST-SERIAL'));assert.ok(html.includes('&lt;script&gt;unsafe'));assert.ok(!html.includes('<script>unsafe'));assert.ok(!html.includes('VAT excluded'));assert.ok(report.buildAssetHistoryReportHtml(asset,[],{owner:true},'','').includes('No matching activity recorded.'));
 if(process.env.HISTORY_REPORT_EVIDENCE){const events=Array.from({length:35},(_,i)=>({...event,id:String(i),action:i===34?'FINAL HISTORY ENTRY':event.action}));const html=report.buildAssetHistoryReportHtml(asset,events,{owner:true},'data:image/png;base64,'+fs.readFileSync('public/brand/aim4price-mark-black.png').toString('base64'),'',new Date('2026-10-05T10:00:00Z'));fs.writeFileSync(process.env.HISTORY_REPORT_EVIDENCE,html);}
});
