const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),{randomUUID}=require('node:crypto'),{PGlite}=require('@electric-sql/pglite');
function load(file,mocks){const exports={};new Function('require','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>{if(n in mocks)return mocks[n];if(n==='node:crypto')return require(n);throw Error('Missing mock '+n)},exports);return exports;}
async function setup(){const pg=new PGlite();const query=(sql,p)=>p?pg.query(sql,p):pg.exec(sql).then(r=>r.at(-1)||{rows:[]});const tx={query,release(){}};const db={getDb:()=>({query,connect:async()=>tx})};const schema=load('lib/asset-history-schema.ts',{'./db':db}),activity=load('lib/shared-asset-activity.ts',{'./db':db});await pg.exec(`CREATE TABLE asset_register_items(id uuid PRIMARY KEY,user_id text,title text,value numeric,year_model int,condition text,note text,specs_json jsonb,updated_at timestamptz);CREATE TABLE asset_invoices(id uuid PRIMARY KEY,user_id text,asset_register_item_id uuid,subtotal_ex_vat numeric,created_by_display_name text);CREATE TABLE fuel_slips(id uuid PRIMARY KEY,user_id text,asset_register_item_id uuid,litres numeric,voided_at timestamptz);CREATE TABLE asset_cost_budgets(id uuid PRIMARY KEY,user_id text,asset_register_item_id uuid,amount numeric);CREATE TABLE asset_maintenance_records(id uuid PRIMARY KEY,user_id text,asset_register_item_id uuid,title text,status text);CREATE TABLE account_documents(id uuid PRIMARY KEY,user_id text,title text,deleted_at timestamptz);CREATE TABLE account_document_asset_links(document_id uuid REFERENCES account_documents(id) ON DELETE CASCADE,asset_id text);`);await schema.installAssetHistoryTriggers();await activity.ensureSharedAssetActivity();const history=load('lib/asset-history.ts',{'./asset-history-fields':load('lib/asset-history-fields.ts',{}),'./db':db,'./asset-history-schema':schema,'./shared-asset-activity':activity});return {pg,schema,history,tx,db};}
test('audit captures asset, cost, fuel, budget, maintenance and document writes atomically; records cannot be erased',async()=>{const {pg,schema,tx}=await setup();try{const asset=randomUUID();await pg.query("INSERT INTO asset_register_items VALUES($1,'owner','Tractor',500000,2023,'good','private','{}',now())",[asset]);await pg.exec('BEGIN');await schema.setAssetHistoryActor(tx,'dealer','Workshop','Leads');await pg.query('UPDATE asset_register_items SET title=$2 WHERE id=$1',[asset,'New tractor']);await pg.exec('COMMIT');let rows=(await pg.query('SELECT * FROM asset_history_events ORDER BY created_at')).rows;assert.equal(rows.length,2);assert.equal(rows[1].actor_id,'dealer');assert.equal(rows[1].before_data.title,'Tractor');assert.equal(rows[1].after_data.title,'New tractor');await pg.exec('BEGIN');await pg.query('UPDATE asset_register_items SET value=1 WHERE id=$1',[asset]);await pg.exec('ROLLBACK');assert.equal((await pg.query('SELECT * FROM asset_history_events')).rows.length,2);
for(const [table,fields,values] of [['asset_invoices','subtotal_ex_vat','100'],['fuel_slips','litres','50'],['asset_cost_budgets','amount','1000'],['asset_maintenance_records','status',"'upcoming'"]]){const id=randomUUID();await pg.query(`INSERT INTO ${table}(id,user_id,asset_register_item_id,${fields}) VALUES($1,'owner',$2,${values})`,[id,asset]);await pg.query(`DELETE FROM ${table} WHERE id=$1`,[id]);const logs=(await pg.query('SELECT * FROM asset_history_events WHERE record_id=$1 ORDER BY created_at',[id])).rows;assert.equal(logs.length,2);assert.equal(logs[1].operation,'DELETE');assert.ok(logs[1].before_data[fields]);}
const doc=randomUUID();await pg.query("INSERT INTO account_documents VALUES($1,'owner','Policy',null)",[doc]);await pg.query('INSERT INTO account_document_asset_links VALUES($1,$2)',[doc,asset]);await pg.query('UPDATE account_documents SET deleted_at=now() WHERE id=$1',[doc]);assert.equal((await pg.query("SELECT * FROM asset_history_events WHERE record_table='account_documents'")).rows.length,1);
await assert.rejects(pg.query('DELETE FROM asset_history_events WHERE asset_id=$1',[asset]),/append-only/);await assert.rejects(pg.query("UPDATE asset_history_events SET actor_name='fake' WHERE asset_id=$1",[asset]),/append-only/);await schema.installAssetHistoryTriggers();await pg.exec(fs.readFileSync('database/migrations/131-unified-asset-history.sql','utf8'));}finally{await pg.close();}});
test('history isolates owners, redacts unauthorized fields and keeps stable pagination for identical timestamps',async()=>{const {pg,history}=await setup();try{const asset=randomUUID(),other=randomUUID();await pg.query("INSERT INTO asset_register_items VALUES($1,'owner','Tractor',100,2023,'good','secret','{}',now()),($2,'other','Private tractor',200,2022,'used','secret','{}',now())",[asset,other]);for(let i=0;i<105;i++)await pg.query("INSERT INTO asset_history_events(owner_id,asset_id,category,record_table,record_id,operation,actor_id,actor_name,source,before_data,after_data,created_at) VALUES('owner',$1::uuid,'details','asset_register_items',$1::text,'UPDATE','owner','Owner','Owner','{}',$2,'2026-10-01')",[asset,JSON.stringify({title:'Change '+i,note:'private',year_model:2020+i})]);const first=await history.listUnifiedAssetHistory('owner',asset);assert.equal(first.items.length,100);assert.ok(first.nextBefore);const next=await history.listUnifiedAssetHistory('owner',asset,{owner:true,before:first.nextBefore});assert.equal(new Set([...first.items,...next.items].map(i=>i.id)).size,106);assert.equal((await history.listUnifiedAssetHistory('other',asset)).items.length,0);const shared=await history.listUnifiedAssetHistory('owner',asset,{owner:false,actorId:'dealer',categories:['details'],detailFields:['year_model']});assert.ok(shared.items.every(i=>!i.href&&!i.restorable&&!('note' in i.after)&&!('title' in i.after)));}finally{await pg.close();}});
test('restoration rejects newer edits and uses the canonical detail writer instead of snapshot replacement',async()=>{const {pg,schema,tx,db}=await setup();try{const asset=randomUUID();await pg.query("INSERT INTO asset_register_items VALUES($1,'owner','Old title',100,2023,'good','note','{}',now())",[asset]);await pg.query("UPDATE asset_register_items SET title='New title' WHERE id=$1",[asset]);const event=(await pg.query("SELECT id FROM asset_history_events WHERE operation='UPDATE'")).rows[0].id;const calls=[];const restore=load('lib/asset-history-restore.ts',{'./asset-usage':load('lib/asset-usage.ts',{}),'./asset-history-fields':load('lib/asset-history-fields.ts',{}),'./db':db,'./asset-history-schema':schema,'./shared-asset-activity':load('lib/shared-asset-activity.ts',{'./db':db}),'./asset-history':{detailsRestore:['title'],historyChanges:(b,a)=>Object.keys(a).filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k]))},'./asset-register-db':{updateSharedAssetDetails:async(client,owner,id,patch)=>{calls.push(patch);await client.query('UPDATE asset_register_items SET title=$2 WHERE id=$1',[id,patch.title]);return {before:{title:'New title'},after:{title:patch.title}};}}});await assert.rejects(restore.restoreAssetDetails('owner',asset,event,{id:'owner',name:'Owner'},false),/Confirm/);await restore.restoreAssetDetails('owner',asset,event,{id:'owner',name:'Owner'},true);assert.deepEqual(calls,[{title:'Old title'}]);await assert.rejects(restore.restoreAssetDetails('owner',asset,event,{id:'owner',name:'Owner'},true),/Newer/);assert.equal((await pg.query('SELECT value FROM asset_register_items WHERE id=$1',[asset])).rows[0].value,'100');}finally{await pg.close();}});

test('replacement email is retry-safe and failure leaves the owner review pending',async()=>{const pg=new PGlite(),previous=process.env.RESEND_API_KEY;process.env.RESEND_API_KEY='fixture-not-a-real-key';try{
 await pg.exec('CREATE TABLE dealer_asset_correction_requests(id uuid PRIMARY KEY,owner_user_id text,asset_register_item_id uuid,dealer_user_id text,status text,replacement_price_changed boolean);CREATE TABLE "user"(id text,email text);INSERT INTO "user" VALUES(\'owner\',\'owner@example.test\');');const id=randomUUID(),asset=randomUUID();await pg.query("INSERT INTO dealer_asset_correction_requests VALUES($1,'owner',$2,'dealer','pending',true)",[id,asset]);const sent=[];let fail=true;
 const db={getDb:()=>({query:(sql,p)=>p?pg.query(sql,p):pg.exec(sql).then(r=>r.at(-1))})};const mail=load('lib/asset-replacement-mail.ts',{'./db':db,'./email':{getSiteOrigin:()=> 'https://example.test',sendAim4priceEmail:async input=>{sent.push(input);if(fail)throw Error('Temporary delivery failure');}}});
 await mail.notifyReplacementSuggestion(id);assert.equal(sent.length,1);assert.equal((await pg.query('SELECT status FROM dealer_asset_correction_requests')).rows[0].status,'pending');assert.match((await pg.query('SELECT error FROM asset_replacement_notifications')).rows[0].error,/failure/);await mail.notifyReplacementSuggestion(id);assert.equal(sent.length,1);
 fail=false;await pg.query("UPDATE asset_replacement_notifications SET attempted_at=now()-interval '20 minutes'");await mail.notifyReplacementSuggestion(id);await mail.notifyReplacementSuggestion(id);assert.equal(sent.length,2);assert.equal(sent[0].idempotencyKey,sent[1].idempotencyKey);assert.ok(sent[1].text.includes('replacementReview='+id));assert.ok((await pg.query('SELECT sent_at FROM asset_replacement_notifications')).rows[0].sent_at);
 }finally{if(previous===undefined)delete process.env.RESEND_API_KEY;else process.env.RESEND_API_KEY=previous;await pg.close();}});

test('legacy usage changes can be retracted by their owner, with newer readings protected',async()=>{
 const {pg,schema,db,history}=await setup();try{
 await pg.exec('ALTER TABLE asset_register_items ADD COLUMN hours numeric');const asset=randomUUID(),event=randomUUID();
 await pg.query("INSERT INTO asset_register_items(id,user_id,title,hours) VALUES($1,'owner','Tractor',1300)",[asset]);
 await pg.query("INSERT INTO shared_asset_activity(id,owner_id,asset_id,actor_id,actor_name,action,before_data,after_data) VALUES($1,'owner',$2,'dealer','Workshop','Asset details updated',$3,$4)",[event,asset,JSON.stringify({usage:1276}),JSON.stringify({usage:1300})]);
 const entry=(await history.listUnifiedAssetHistory('owner',asset,{owner:true})).items.find(i=>i.id===event);assert.equal(entry.restorable,true);
 const restore=load('lib/asset-history-restore.ts',{'./asset-usage':load('lib/asset-usage.ts',{}),'./asset-history-fields':load('lib/asset-history-fields.ts',{}),'./db':db,'./asset-history-schema':schema,'./shared-asset-activity':load('lib/shared-asset-activity.ts',{'./db':db}),'./asset-register-db':{updateSharedAssetDetails:async(client,owner,id,patch,options)=>{assert.equal(options.allowUsageDecrease,true);assert.equal(patch.usage,1276);await client.query('UPDATE asset_register_items SET hours=$2 WHERE id=$1',[id,patch.usage]);return {before:{usage:1300},after:{usage:patch.usage}};}}});
 await assert.rejects(restore.restoreAssetDetails('other',asset,event,{id:'other',name:'Other'},true),/cannot be retracted/);
 await pg.query('UPDATE asset_register_items SET hours=1400 WHERE id=$1',[asset]);await assert.rejects(restore.restoreAssetDetails('owner',asset,event,{id:'owner',name:'Owner'},true),/Newer changes/);
 await pg.query('UPDATE asset_register_items SET hours=1300 WHERE id=$1',[asset]);await restore.restoreAssetDetails('owner',asset,event,{id:'owner',name:'Owner'},true);
 assert.equal((await pg.query('SELECT hours FROM asset_register_items WHERE id=$1',[asset])).rows[0].hours,'1276');
 assert.equal((await pg.query('SELECT * FROM shared_asset_activity WHERE id=$1',[event])).rows.length,1);
 assert.equal((await pg.query("SELECT * FROM shared_asset_activity WHERE action='Asset change retracted'")).rows.length,1);
 }finally{await pg.close();}
});

test('value history restores the prior depreciation basis, requires preview confirmation and protects newer changes',async()=>{
 const {pg,db,schema,history}=await setup();try{
 const asset=randomUUID(),event=randomUUID();const previous={version:1,amount:500,modelValue:1000,date:'2025-01-01',eventId:randomUUID()},latest={...previous,amount:300,eventId:event};
 await pg.query("INSERT INTO asset_register_items VALUES($1,'owner','Tractor',300,2023,'good','keep this note',$2,now())",[asset,JSON.stringify({approved_value_baseline:latest,unrelated:'keep'})]);
 const activity=load('lib/shared-asset-activity.ts',{'./db':db});
 await activity.recordSharedAssetActivity({query:(s,p)=>pg.query(s,p)},{id:event,ownerId:'owner',assetId:asset,actorId:'owner',actorName:'Owner',action:'Value overridden',before:{amount:500,replacementPrice:1000,baseline:previous},after:{amount:300,replacementPrice:null,baseline:latest}});
 await pg.query("UPDATE shared_asset_activity SET created_at='2026-10-05 13:15:00.123456+00' WHERE id=$1",[event]);
 const truncated=new Date('2026-10-05T13:15:00.123Z');assert.equal((await pg.query('SELECT 1 FROM shared_asset_activity WHERE id=$1 AND created_at>$2::timestamptz',[event,truncated])).rows.length,1,'JavaScript timestamps lose database microseconds');
 const get=async(owner,id,client)=>{const row=(await (client||db.getDb()).query('SELECT * FROM asset_register_items WHERE user_id=$1 AND id=$2',[owner,id])).rows[0];return row?{id,userId:owner,value:Number(row.value),replacementPriceExVat:1000,specsJson:row.specs_json,updatedAtIso:new Date(row.updated_at).toISOString(),selectedMethod:'aim4price'}:null;};
 const restore=load('lib/asset-value-history-restore.ts',{'./db':db,'./asset-history-schema':schema,'./shared-asset-activity':activity,'./approved-value-baseline':load('lib/approved-value-baseline.ts',{}),'./asset-register-revaluation':{revalueAssetRegisterItem:async()=>({newValueExVat:800})},'./asset-register-db':{getAssetRegisterItemById:get,saveApprovedAssetValue:async(client,a,value,baseline)=>{await client.query("UPDATE asset_register_items SET value=$2,specs_json=jsonb_set(specs_json,'{approved_value_baseline}',$3::jsonb),updated_at=clock_timestamp() WHERE id=$1",[a.id,value,JSON.stringify(baseline)]);}}});
 const entry=(await history.listUnifiedAssetHistory('owner',asset)).items.find(i=>i.id===event);assert.equal(entry.valueRestorable,true);assert.equal((await history.listUnifiedAssetHistory('owner',asset,{owner:false,actorId:'owner'})).items.some(i=>i.valueRestorable),false);
 const actor={id:'owner',name:'Owner'},preview=await restore.restoreAssetValueHistory('owner',asset,event,actor,{action:'previewValueRestore'});assert.equal(preview.previousValue,400,'restores the old curve at today’s model value, not the old amount or a new anchor');
 await assert.rejects(restore.restoreAssetValueHistory('other',asset,event,actor,{action:'previewValueRestore'}),/history entry/);
 await assert.rejects(restore.restoreAssetValueHistory('owner',asset,event,actor,{confirmed:true,revision:preview.revision,expectedValue:500}),/Newer/);
 await assert.rejects(restore.restoreAssetValueHistory('owner',asset,event,actor,{confirmed:false}),/Confirm/);
 await assert.rejects(restore.restoreAssetValueHistory('owner',asset,event,actor,{confirmed:true,revision:preview.revision,expectedValue:400},async()=>{throw Error('Access revoked');}),/Access revoked/);
 await restore.restoreAssetValueHistory('owner',asset,event,actor,{confirmed:true,revision:preview.revision,expectedValue:400});
 const saved=await get('owner',asset);assert.equal(saved.value,400);assert.deepEqual(saved.specsJson.approved_value_baseline,previous);assert.equal(saved.specsJson.unrelated,'keep');assert.equal((await pg.query('SELECT note FROM asset_register_items WHERE id=$1',[asset])).rows[0].note,'keep this note');
 assert.equal((await pg.query("SELECT count(*)::int AS n FROM shared_asset_activity WHERE action='Value restored'")).rows[0].n,1);await assert.rejects(restore.restoreAssetValueHistory('owner',asset,event,actor,{action:'previewValueRestore'}),/Newer/);
 }finally{await pg.close();}
});

test('manual restoration uses the exact saved amount and a missing prior baseline returns to the original automatic curve',async()=>{
 for(const manual of [true,false]){
 const eventId=randomUUID(),baseline={version:1,amount:300,modelValue:manual?null:1000,date:'2026-10-05',eventId},previous={amount:327133,replacementPrice:500000,baseline:null};let saved;
 const asset={id:'asset',userId:'owner',value:300000,replacementPriceExVat:500000,selectedMethod:manual?'manual':'automatic',updatedAtIso:'v1',specsJson:{approved_value_baseline:baseline}};
 const query=async sql=>({rows:sql.includes('SELECT s.*')?[{id:eventId,before_data:previous,after_data:{amount:300000,baseline,replacementPrice:null},created_at:'2026-10-05'}]:[]});
 const db={getDb:()=>({query,connect:async()=>({query,release(){}})})};
 const restore=load('lib/asset-value-history-restore.ts',{'./db':db,'./asset-history-schema':{ensureAssetHistorySchema:async()=>{},setAssetHistoryActor:async()=>{}},'./shared-asset-activity':{ensureSharedAssetActivity:async()=>{},recordSharedAssetActivity:async()=>{}},'./approved-value-baseline':load('lib/approved-value-baseline.ts',{}),'./asset-register-revaluation':{revalueAssetRegisterItem:async()=>{assert.equal(manual,false);return {newValueExVat:320000};}},'./asset-register-db':{getAssetRegisterItemById:async()=>asset,saveApprovedAssetValue:async(c,a,value,b)=>{saved={value,baseline:b};}}});
 const preview=await restore.restoreAssetValueHistory('owner','asset',eventId,{id:'owner',name:'Owner'},{action:'previewValueRestore'});
 assert.equal(preview.previousValue,manual?327133:320000);await restore.restoreAssetValueHistory('owner','asset',eventId,{id:'owner',name:'Owner'},{confirmed:true,revision:'v1',expectedValue:preview.previousValue});assert.deepEqual(saved,{value:preview.previousValue,baseline:null});
 }
});
