import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import ts from 'typescript';
import {PGlite} from '@electric-sql/pglite';
const require=createRequire(import.meta.url);
function load(file,deps={}){const code=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const module={exports:{}};Function('require','module','exports',code)(id=>id in deps?deps[id]:require(id),module,module.exports);return module.exports;}
const shared=load('lib/billing-shared.ts'),schema=load('lib/billing-schema.ts');
const report=load('lib/billing-report.ts',{'./billing-shared':shared,'./report-theme':load('lib/report-theme.ts')});
test('money, quantities, calendar dates and no-VAT totals are validated without float parsing',()=>{
 assert.equal(shared.moneyToCents('1 234.56'),123456);assert.equal(shared.moneyToCents('0.10'),10);
 for(const v of ['-1','1.001','1e3','abc','Infinity'])assert.throws(()=>shared.moneyToCents(v));
 assert.throws(()=>shared.validDate('2026-02-30'));assert.equal(shared.nextBillingDate('2026-01-31','monthly'),'2026-02-28');
 assert.equal(shared.nextBillingDate('2024-02-29','annual'),'2025-02-28');
 assert.deepEqual(shared.cleanLines([{description:'Service',quantity:3,unitCents:1999}])[0].totalCents,5997);
 assert.throws(()=>shared.cleanLines([{description:'Service',quantity:-1,unitCents:1999}]));
 assert.equal(schema.BILLING_SCHEMA_SQL,readFileSync(new URL('../database/migrations/110-aim4price-billing.sql',import.meta.url),'utf8'));
});
test('invoice lifecycle, signup, ownership, work reservations, payment idempotency and durable mail retries',async()=>{
 const pg=new PGlite();
 const query=async(sql,values)=>{if(sql===schema.BILLING_SCHEMA_SQL){await pg.exec(sql);return {rows:[],rowCount:0};}if(sql.includes('pg_advisory_xact_lock'))return {rows:[],rowCount:1};const result=await pg.query(sql,values);return {...result,rowCount:result.rows.length||result.affectedRows||0};};
 const db={query,connect:async()=>({query,release(){}})};
 const billing=load('lib/billing.ts',{'./db':{getDb:()=>db},'./billing-schema':schema,'./billing-shared':shared,'./billing-report':report,'./admin-work-tracker':{ensureAdminWorkTrackerSchema:async()=>{}}});
 const oldFetch=global.fetch,oldKey=process.env.RESEND_API_KEY;
 try{
  await pg.exec('create table "user"(id text primary key,name text,email text); create table account_profiles(user_id text primary key,business_name text,address_line_1 text,address_line_2 text,town_city text,province text,phone text); create table admin_work_sessions(id text primary key,client_user_id text,started_at timestamptz default now(),stopped_at timestamptz,duration_seconds integer,note text);');
  await pg.exec("insert into \"user\" values('one','Customer One','one@example.test'),('two','Customer Two','two@example.test');insert into admin_work_sessions(id,client_user_id,stopped_at,duration_seconds,note) values('work-one','one',now(),5400,'Capture work'),('work-two','two',now(),3600,'Private work'),('running','one',null,3600,'Still running');");
  await billing.ensureBillingSchema();
  await pg.exec("insert into account_profiles values('one','Farm Business','Road 10','Unit 2','George','Western Cape','0821234567')");
  const initialWorkspace=await billing.getBillingWorkspace('one');
  assert.equal(initialWorkspace.customer.businessName,'Farm Business');assert.equal(initialWorkspace.customer.address,'Road 10\nUnit 2\nGeorge\nWestern Cape');
  const customer={name:'Customer One',email:'one@example.test',address:'George'};
  const draft={id:randomUUID(),userId:'one',customer,lines:[{description:'Subscription',quantity:1,unitCents:10000}],dueDate:'2026-09-30',workSessionIds:['work-one'],hourlyRateCents:20000};
  await billing.createBillingDraft(draft,'admin');await billing.createBillingDraft(draft,'admin');
  const listed=await billing.listBillingInvoices('one',true);assert.equal(listed.total,1);assert.equal(listed.invoices[0].contactPhone,'0821234567');assert.equal(listed.invoices[0].contactEmail,'one@example.test');
  const savedWorkspace=await billing.getBillingWorkspace('one');assert.equal(savedWorkspace.customer.address,'George');assert.equal(savedWorkspace.accountCustomer.address,'Road 10\nUnit 2\nGeorge\nWestern Cape');
  let inv=await billing.getBillingInvoice(draft.id,null,true);assert.equal(Number(inv.total_cents),40000);
  await assert.rejects(billing.getBillingInvoice(draft.id,'one',false),/not found/);
  for(const work of ['work-one','work-two','running'])await assert.rejects(billing.createBillingDraft({...draft,id:randomUUID(),workSessionIds:[work]},'admin'));
  await billing.actOnBillingInvoice(draft.id,{action:'update_draft',version:1,customer,lines:[{description:'Updated subscription',quantity:1,unitCents:12000}],dueDate:'2026-09-30'},'admin');
  await assert.rejects(billing.actOnBillingInvoice(draft.id,{action:'issue',version:1},'admin'),/changed/);
  await billing.actOnBillingInvoice(draft.id,{action:'issue',version:2},'admin');await billing.actOnBillingInvoice(draft.id,{action:'issue',version:2},'admin');
  inv=await billing.getBillingInvoice(draft.id,'one',false);assert.match(inv.number,/^A4P-\d{4}-\d{6}$/);assert.equal(Number(inv.total_cents),42000);assert.match(inv.report_html,/No VAT applicable/);assert.match(inv.report_html,/4113 0591 64/);
  await assert.rejects(billing.getBillingInvoice(draft.id,'two',false),/not found/);
  await assert.rejects(billing.actOnBillingInvoice(draft.id,{action:'delete_draft'},'admin'),/cannot be deleted/);
  await assert.rejects(billing.actOnBillingInvoice(draft.id,{action:'update_draft',version:3},'admin'),/issued/);
  const pay={action:'payment',paymentId:randomUUID(),amountCents:10000,paymentDate:shared.dateKey(),reference:'EFT-001'};
  await billing.actOnBillingInvoice(draft.id,pay,'admin');await billing.actOnBillingInvoice(draft.id,pay,'admin');
  assert.equal(Number((await billing.getBillingInvoice(draft.id,'one',false)).paid_cents),10000);
  await assert.rejects(billing.actOnBillingInvoice(draft.id,{...pay,paymentId:randomUUID(),amountCents:50000},'admin'),/remaining balance/);
  await assert.rejects(billing.actOnBillingInvoice(draft.id,{action:'void',reason:'Correction'},'admin'),/unpaid/);
  const localDraft={...draft,id:randomUUID(),workSessionIds:[],customer:{...customer,businessName:'Example Business',reference:'PO-99'}};
  await billing.createBillingDraft(localDraft,'admin');
  await billing.actOnBillingInvoice(localDraft.id,{action:'issue',version:1,sendEmail:false},'admin');
  await billing.actOnBillingInvoice(localDraft.id,{action:'issue',version:1,sendEmail:false},'admin');
  const localInvoice=await billing.getBillingInvoice(localDraft.id,'one',false);
  assert.ok(localInvoice.number);assert.match(localInvoice.report_html,/Example Business/);assert.match(localInvoice.report_html,/PO-99/);
  assert.equal((await pg.query('select count(*)::int as n from aim4price_billing_mail where invoice_id=$1',[localDraft.id])).rows[0].n,0);
  await billing.saveBillingPlan({accountType:'owner',description:'Monthly subscription',amountCents:50000,interval:'monthly',dueDays:7,enabled:true});
  await assert.rejects(billing.validateSignupBilling({accountType:'owner',accountSubtype:'equipment-middleman'}),/accept/);
  assert.equal(await billing.validateSignupBilling({accountType:'dealer',accountSubtype:'equipment-middleman'}),null);
  await assert.rejects(billing.validateSignupBilling({accountType:'owner',billingAccepted:true,billingPlanVersion:0}),/current/);
  const quote=await billing.validateSignupBilling({accountType:'owner',billingAccepted:true,billingPlanVersion:1,billingName:customer.name,billingEmail:customer.email,billingAddress:customer.address});
  await billing.queueSignupInvoice('two',quote);await billing.processSignupInvoices();await billing.processSignupInvoices();
  assert.equal((await billing.listBillingInvoices('two',false)).total,1);
  assert.equal((await pg.query("select count(*)::int as n from aim4price_billing_mail where invoice_id=$1",[draft.id])).rows[0].n,1);
  const mail=load('lib/billing-mail.ts',{'./db':{getDb:()=>db},'./billing':billing,'./report-pdf':{renderReportHtmlToPdf:async()=>Buffer.from('%PDF-fixture')},'./email':{getSiteOrigin:()=> 'https://aim4price.test'},'./billing-report':report,'./billing-shared':shared});
  const calls=[];process.env.RESEND_API_KEY='fake-test-key';
  global.fetch=async(url,options)=>{calls.push({url,options});throw Error('Simulated network timeout');};
  await mail.dispatchBillingMail();
  assert.equal(calls.length,2);
  assert.equal((await pg.query('select status from aim4price_billing_mail where invoice_id=$1',[draft.id])).rows[0].status,'retry');
  await pg.query("update aim4price_billing_mail set next_attempt_at=now()-interval '1 minute'");
  global.fetch=async(url,options)=>{calls.push({url,options});return Response.json({id:'email-test'});};
  await mail.dispatchBillingMail();assert.equal(calls.length,4);
  assert.equal(calls[0].options.body,calls[2].options.body);assert.equal(calls[0].options.headers['Idempotency-Key'],calls[2].options.headers['Idempotency-Key']);
  assert.equal((await pg.query('select status from aim4price_billing_mail where invoice_id=$1',[draft.id])).rows[0].status,'accepted');
  await billing.actOnBillingInvoice(draft.id,{action:'send',confirmed:true},'admin');
  await pg.query("update aim4price_billing_mail set status='retry',first_attempt_at=now()-interval '25 hours' where status='queued'");
  await mail.dispatchBillingMail();assert.equal(calls.length,4);assert.equal((await pg.query("select count(*)::int as n from aim4price_billing_mail where status='needs_review'")).rows[0].n,1);
 }finally{global.fetch=oldFetch;if(oldKey===undefined)delete process.env.RESEND_API_KEY;else process.env.RESEND_API_KEY=oldKey;await pg.close();}
});

test('recurring agreements are opt-in, audited, versioned and issue only once per scheduled period',async()=>{
 const pg=new PGlite();
 const query=async(sql,values)=>{if(sql===schema.BILLING_SCHEMA_SQL){await pg.exec(sql);return {rows:[],rowCount:0};}if(sql.includes('pg_advisory_xact_lock'))return {rows:[],rowCount:1};const r=await pg.query(sql,values);return {...r,rowCount:r.rows.length||r.affectedRows||0};};
 const db={query,connect:async()=>({query,release(){}})};
 const billing=load('lib/billing.ts',{'./db':{getDb:()=>db},'./billing-schema':schema,'./billing-shared':shared,'./billing-report':report,'./admin-work-tracker':{ensureAdminWorkTrackerSchema:async()=>{}}});
 try {
  await pg.exec('create table "user"(id text primary key,name text,email text); insert into "user" values(\'one\',\'Example\',\'one@example.test\');');
  await pg.exec('create table account_profiles(user_id text primary key,phone text)');
  await billing.ensureBillingSchema();
  const input={userId:'one',version:0,customer:{name:'Example',email:'one@example.test',address:'George'},lines:[{description:'Approved package',quantity:1,unitCents:25000}],interval:'monthly',nextInvoiceDate:'2090-01-31',dueDays:7,enabled:false};
  await billing.saveBillingAgreement(input,'admin');
  await billing.processRecurringInvoices('2090-01-31');
  assert.equal((await billing.listBillingInvoices('one',true)).total,0);
  await assert.rejects(billing.saveBillingAgreement({...input,version:1,enabled:true},'admin'),/agreed/);
  await assert.rejects(billing.saveBillingAgreement({...input,version:0},'admin'),/changed/);
  await billing.saveBillingAgreement({...input,version:1,enabled:true,approved:true},'admin');
  await billing.processRecurringInvoices('2090-01-31');await billing.processRecurringInvoices('2090-01-31');
  let a=await billing.getBillingAgreement('one');
  assert.equal(a.nextInvoiceDate,'2090-02-28');
  assert.equal((await billing.listBillingInvoices('one',false)).total,1);
  assert.equal((await pg.query('select count(*)::int as n from aim4price_billing_mail')).rows[0].n,1);
  await billing.processRecurringInvoices('2090-02-28');
  a=await billing.getBillingAgreement('one');assert.equal(a.nextInvoiceDate,'2090-03-31');
  await assert.rejects(billing.saveBillingAgreement({...input,version:a.version,nextInvoiceDate:'2090-02-28'},'admin'),/already been invoiced/);
  await billing.pauseBillingAgreement({userId:'one',version:a.version,reason:'Customer requested a pause'},'admin');
  await billing.processRecurringInvoices('2090-03-31');assert.equal((await billing.listBillingInvoices('one',false)).total,2);
  a=await billing.getBillingAgreement('one');
  await billing.saveBillingAgreement({...input,version:a.version,nextInvoiceDate:'2090-03-31',enabled:true,approved:true},'admin');
  await billing.processRecurringInvoices('2090-05-01');
  a=await billing.getBillingAgreement('one');assert.equal(a.enabled,false);assert.match(a.lastError,/Missed billing/);
  assert.equal((await billing.listBillingInvoices('one',false)).total,2);
  const events=await pg.query('select actor_id,action from aim4price_billing_agreement_events');
  assert.ok(events.rows.some(e=>e.actor_id==='admin'&&e.action==='paused'));
  assert.ok(events.rows.some(e=>e.action==='review_required'));
  assert.equal(shared.nextAgreementDate('2025-02-28','annual','2024-02-29'),'2026-02-28');
  assert.equal(shared.nextAgreementDate('2027-02-28','annual','2024-02-29'),'2028-02-29');
 } finally {await pg.close();}
});

test('account defaults, business name and customer references survive validation and PDF HTML',async()=>{
 const defaults=shared.billingAccountCustomer({name:'Contact',email:'contact@example.test'},{business_name:'Example Farming',address_line_1:'Farm Road 10',address_line_2:'Unit 2',town_city:'George',province:'Western Cape'});
 assert.equal(defaults.businessName,'Example Farming');assert.equal(defaults.address,'Farm Road 10\nUnit 2\nGeorge\nWestern Cape');
 const customer=shared.cleanCustomer({...defaults,reference:'PO-123 <test>'});
 assert.equal(customer.reference,'PO-123 <test>');
 assert.throws(()=>shared.cleanCustomer({...defaults,reference:'x'.repeat(121)}));
 const invoice={id:'test',number:null,status:'draft',customer,lines:[{description:'Service',quantity:1,unitCents:10000,totalCents:10000}],totalCents:10000,dueDate:'2090-01-01',note:''};
 const html=await report.buildBillingInvoiceHtml(invoice);
 assert.match(html,/Example Farming/);assert.match(html,/PO-123 &lt;test&gt;/);assert.match(html,/DRAFT - NOT ISSUED/);
 const issued=await report.buildBillingInvoiceHtml({...invoice,status:'issued',number:'A4P-TEST',issuedAt:'2026-09-27T00:00:00Z'});
 assert.doesNotMatch(issued,/DRAFT - NOT ISSUED|Draft for review|Draft only/);
});

test('share links normalize saved contacts and safely encode invoice messages',()=>{
 const invoice={status:'issued',number:'A4P-2026-000001',customer:{name:'Name & Co'},contactPhone:'082 123 4567',contactEmail:'saved@example.test'};
 const links=shared.billingContactLinks(invoice);
 assert.equal(new URL(links.whatsapp).pathname,'/27821234567');
 assert.match(new URL(links.whatsapp).searchParams.get('text'),/Name & Co/);
 assert.match(links.email,/^mailto:saved%40example.test\?subject=/);
 for(const phone of ['+27 (82) 123-4567','0027821234567'])assert.equal(new URL(shared.billingContactLinks({...invoice,contactPhone:phone}).whatsapp).pathname,'/27821234567');
 for(const phone of ['', 'phone 0821234567','+27+821234567','123'])assert.equal(shared.billingContactLinks({...invoice,contactPhone:phone}).whatsapp,null);
 for(const email of ['', 'a@example.test,b@example.test','a@example.test\r\nBcc: other@example.test'])assert.equal(shared.billingContactLinks({...invoice,contactEmail:email}).email,null);
 const draft=shared.billingContactLinks({...invoice,status:'draft',number:null});assert.match(new URL(draft.whatsapp).searchParams.get('text'),/preparing/);assert.doesNotMatch(new URL(draft.whatsapp).searchParams.get('text'),/signing in/);
});
