const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const {PGlite}=require('@electric-sql/pglite');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>{if(n in mocks)return mocks[n];throw Error('Missing mock '+n);},m,m.exports);return m.exports;}
const id='10000000-0000-4000-8000-000000000001',assetId='20000000-0000-4000-8000-000000000001',nextId='10000000-0000-4000-8000-000000000002';
async function setup(){const pg=new PGlite();await pg.exec(`CREATE TABLE "user"(id text,email text,name text,"emailVerified" boolean DEFAULT true);INSERT INTO "user" VALUES('owner','owner@test.example','Owner',true),('scheduler','workshop@test.example','Workshop',true);CREATE TABLE asset_maintenance_records(id uuid,user_id text,status text,generated_from_maintenance_id uuid);INSERT INTO asset_maintenance_records VALUES('${id}','owner','upcoming',null);`);const query=(sql,p)=>p?pg.query(sql,p):pg.exec(sql).then(r=>r.at(-1));const db={query};let revoked=false,fail=false;const sent=[];const record={id,userId:'owner',assetId,assetTitle:'Tractor <test>',title:'Oil service',maintenanceType:'service',status:'upcoming',computedStatus:'due_soon',triggerType:'usage',dueUsage:1500,usageMetric:'hours',updatedAtIso:'2026-10-05T10:00:00Z'};const profile={accountType:'dealer',accountStatus:'active'};const api=load('lib/maintenance-reminders.ts',{'./db':{getDb:()=>db},'./account-profile':{getAccountProfile:async()=>profile},'./business-accounts':{canBusinessRead:async()=>true,canBusinessContribute:async()=>false},'./sharing-foundation':{sharingPlan:async()=> 'paid'},'./asset-maintenance':{ensureAssetMaintenanceTables:async()=>{},listAssetMaintenanceRecords:async owner=>owner==='owner'?[record]:[],getAssetMaintenanceRecordById:async()=>record},'./email':{getSiteOrigin:()=> 'https://example.test',sendAim4priceEmail:async m=>{if(fail)throw Error('Provider unavailable');sent.push(m);}},'./guest-leads':{readLeadPage:async()=>revoked?null:{ownerId:'owner',share:{assets:[{assetId}]},details:{recipientEmail:'workshop@test.example'}}},'./live-shared-asset-access':{lockLiveSharedAsset:async()=>{if(revoked)throw Error('Revoked');}},'./asset-register-db':{getAssetRegisterItemById:async()=>({serialNumber:'VIN123'})}});await api.ensureMaintenanceReminders();return {api,pg,db,record,sent,profile,revoke:()=>revoked=true,fail:v=>fail=v};}
test('reminder stages stop after completion; overdue shares the due delivery key',async()=>{const x=await setup();try{assert.equal(x.api.reminderStage(x.record),'soon');assert.equal(x.api.reminderStage({...x.record,computedStatus:'overdue'}),'due');assert.equal(x.api.reminderStage({...x.record,status:'done'}),null);assert.equal(x.api.reminderStage({...x.record,status:'cancelled'}),null);}finally{await x.pg.close();}});
test('owner and actual scheduler receive separate once-only stage emails; recurring records retain scheduler',async()=>{process.env.RESEND_API_KEY='test';const x=await setup();try{await x.api.saveMaintenanceSource(x.db,{record_id:id,owner_id:'owner',asset_id:assetId,scheduler_id:'scheduler',access_id:null,share_token:'token'});assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,2);assert.deepEqual(x.sent.map(m=>m.to).sort(),['owner@test.example','workshop@test.example']);assert.match(x.sent[0].html,/Workshop scheduled/);assert.match(x.sent[0].html,/Tractor &lt;test&gt;/);assert.match(x.sent[0].text,/VIN123/);assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,0);x.record.computedStatus='due';assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,2);x.record.computedStatus='overdue';assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,0);await x.pg.query('INSERT INTO asset_maintenance_records VALUES($1,\'owner\',\'upcoming\',$2)',[nextId,id]);assert.equal((await x.api.maintenanceSource(nextId)).scheduler_id,'scheduler');}finally{await x.pg.close();}});
test('revoked shares are excluded from reminders and notifications; owner receives one copy',async()=>{const x=await setup();try{await x.api.saveMaintenanceSource(x.db,{record_id:id,owner_id:'owner',asset_id:assetId,scheduler_id:'scheduler',access_id:null,share_token:'token'});x.revoke();assert.equal((await x.api.listMaintenanceReminderNotifications('scheduler')).length,0);assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,1);assert.equal(x.sent[0].to,'owner@test.example');x.record.status='done';assert.equal((await x.api.listMaintenanceReminderNotifications('owner')).length,0);assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,0);}finally{await x.pg.close();}});
test('provider errors persist and retry after cooldown using the same idempotency key',async()=>{const x=await setup();try{x.fail(true);assert.equal((await x.api.sendMaintenanceReminderBatch()).failed,1);assert.equal((await x.api.sendMaintenanceReminderBatch()).failed,0);assert.match((await x.pg.query('SELECT error FROM maintenance_reminder_deliveries')).rows[0].error,/Provider/);await x.pg.exec("UPDATE maintenance_reminder_deliveries SET attempted_at=now()-interval '16 minutes'");x.fail(false);assert.equal((await x.api.sendMaintenanceReminderBatch()).sent,1);assert.equal(x.sent[0].idempotencyKey,`maintenance:${id}:owner:soon`);}finally{await x.pg.close();}});
test('value email identifies asset and amounts, safely escapes text, and links to exact decision',()=>{const api=load('lib/value-suggestion-email.ts');const m=api.valueSuggestionEmail({title:'Tractor',serial:'VIN',actor:'<Dealer>',before:100,amount:120,reason:'<script>bad</script>',url:`https://example.test/value-review/${assetId}/${id}`});assert.ok(m.text.includes('VIN'));assert.ok(m.text.includes(id));assert.ok(m.html.includes('&lt;Dealer&gt;'));assert.ok(!m.html.includes('<script>'));});
test('maintenance action endpoint blocks other users and revoked access before completion, then rechecks writes',async()=>{
 const sessions={user:{id:'scheduler',email:'s@test.example',name:'Workshop'}};let allowed=true,writeAllowed=true,completed=0,beforeChecked=false;
 const record={id,userId:'owner',assetId,status:'upcoming',assetValue:100000};const source={scheduler_id:'scheduler'};
 const api=load('app/api/maintenance-reminders/[id]/route.ts',{
 '../../../../lib/sharing-foundation':{ensureSharingFoundation:async()=>{},recordSharingUsage:async()=>{}},
 '../../../../lib/auth-session':{getServerSession:async()=>sessions,isOwnerAppSession:()=>false,isDealerAppSession:()=>false},
 '../../../../lib/asset-register-account-access':{getAssetRegisterAccountAccess:async()=>true},
 '../../../../lib/owner-app-access':{},
 '../../../../lib/business-network-api':{businessJson:(body,status=200)=>({body,status}),businessBody:async()=>({}),requireBusinessOrigin:()=>{}},
 '../../../../lib/maintenance-reminders':{reminderRecord:async()=>record,maintenanceSource:async()=>source,schedulerPermission:async(s,u,write)=>u.id===s.scheduler_id&&allowed&&(!write||writeAllowed)},
 '../../../../lib/asset-maintenance':{completeAssetMaintenanceRecord:async(owner,r,body,guard)=>{await guard.before({query:async()=>({rows:[]})});beforeChecked=true;completed++;return {completed:{status:'done'}};}},
 '../../../../lib/asset-checklist-db':{listAssetChecklistItems:async()=>[]},
 '../../../../lib/db':{getDb:()=>({query:async()=>({rows:[{name:'Workshop'}]})})},
 '../../../../lib/asset-history-schema':{setAssetHistoryActor:async()=>{}},
 });
 const get={method:'GET',nextUrl:new URL('https://example.test')},post={...get,method:'POST'};
 assert.equal((await api.GET(get,{params:{id}})).status,200);
 assert.equal((await api.GET(get,{params:{id}})).body.record.assetValue,undefined);
 sessions.user.id='other';assert.equal((await api.POST(post,{params:{id}})).status,403);
 sessions.user.id='scheduler';allowed=false;assert.equal((await api.POST(post,{params:{id}})).status,403);
 allowed=true;writeAllowed=false;assert.equal((await api.POST(post,{params:{id}})).status,403);
 writeAllowed=true;record.status='done';assert.equal((await api.POST(post,{params:{id}})).status,409);
 record.status='upcoming';assert.equal((await api.POST(post,{params:{id}})).status,200);assert.equal(completed,1);assert.equal(beforeChecked,true);
});

test('business scheduler on a targeted share needs owner permission, not business review',async()=>{const x=await setup();try{x.profile.accountType='business';const source={record_id:id,owner_id:'owner',asset_id:assetId,scheduler_id:'scheduler',access_id:null,share_token:'token'};assert.equal(await x.api.schedulerPermission(source,{id:'scheduler',email:'workshop@test.example'},true),true);x.revoke();assert.equal(await x.api.schedulerPermission(source,{id:'scheduler',email:'workshop@test.example'},true),false);}finally{await x.pg.close();}});
