const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),{randomUUID}=require('node:crypto');
function load(file,mocks={}){const exports={};new Function('require','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>n in mocks?mocks[n]:require(n),exports);return exports;}
test('shared paperwork and location require explicit grants, recheck revocation, keep owner scope and count retries once',async()=>{
 class Denied extends Error{constructor(message,status=403){super(message);this.status=status}}
 const asset={id:randomUUID(),title:'Test vehicle',kind:'vehicle',isFinanced:false,isInsured:false,isLicensed:false,specsJson:{privateKey:'preserved'},lastKnownLat:null,lastKnownLng:null,lastKnownLocationText:null};
 const allowed=new Set(),events=new Map(),writes=[],usage=[];let revoked=false,origin=true;
 const client={query:async(sql,params)=>({rows:sql.startsWith('SELECT owner_id')&&events.has(params[0])?[events.get(params[0])]:[]}),release(){}};
 const scope={ownerId:'owner',assetId:asset.id,user:{id:'recipient',name:'Mechanic'},token:'token',lock:async tx=>{assert.equal(tx,client);if(revoked)throw new Denied('revoked')}};
 const canonical={getAssetRegisterItemById:async(owner,id)=>{assert.equal(owner,'owner');assert.equal(id,asset.id);return asset},updateAssetRegisterItemStatusDetails:async(owner,input,tx)=>{assert.equal(owner,'owner');assert.equal(input.assetId,asset.id);assert.equal(tx,client);assert.equal(input.specsJson.privateKey,undefined);writes.push(input);return {...asset,...input}},updateAssetRegisterItemLocation:async(owner,input,tx)=>{assert.equal(owner,'owner');assert.equal(input.assetId,asset.id);assert.equal(tx,client);writes.push(input);return {...asset,lastKnownLat:input.latitude,lastKnownLng:input.longitude,lastKnownLocationText:input.locationText}}};
 const api=load('lib/shared-asset-settings.ts',{'./db':{getDb:()=>({connect:async()=>client})},'./shared-asset-contributions':{contributionScope:async(target,p)=>{if(!allowed.has(p))throw new Denied('not shared');return scope}},'./asset-register-db':canonical,'./shared-asset-status-input':load('lib/shared-asset-status-input.ts'),'./shared-asset-activity':{ensureSharedAssetActivity:async()=>{},recordSharedAssetActivity:async(tx,event)=>{events.set(event.id,{owner_id:event.ownerId,asset_id:event.assetId,actor_id:event.actorId,action:event.action});}},'./sharing-foundation':{ensureSharingFoundation:async()=>{},recordSharingUsage:async data=>usage.push(data)},'./fuel-ledger':{ensureFuelLedgerTables:async()=>{}},'./business-network-api':{businessJson:(data,status=200)=>({data,status}),businessError:e=>({status:400,error:e.message}),businessBody:r=>r.json(),requireBusinessOrigin:()=>{if(!origin)throw new Denied('origin')}},'./external-lead-access':{ExternalLeadAccessError:Denied},'./business-network':{limitBusinessAction:async()=>{}}});
 const send=(action,body,method='POST')=>api.sharedAssetSettings(new Request('https://test/'+action,{method,...(method==='POST'?{body:JSON.stringify(body)}:{})}),{token:'token',assetId:asset.id},action);
 const insurance={requestId:randomUUID(),section:'insurance',insuranceStatus:'yes',insuredValueExVat:120000,insuranceInsurerName:'Example',insuranceRenewalDate:'2027-02-01',assetId:'foreign',specsJson:{privateKey:'attack'}};
 assert.equal((await send('paperwork',null,'GET')).status,403);allowed.add('yearModel');assert.equal((await send('paperwork',insurance)).status,403);
 allowed.add('updateDetails');const read=await send('paperwork',null,'GET');assert.equal(read.status,200);assert.equal(read.data.draft.privateKey,undefined);
 assert.equal((await send('paperwork',{...insurance,insuranceRenewalDate:'2027-02-30'})).status,400);
 assert.equal((await send('paperwork',insurance)).status,200);assert.equal((await send('paperwork',insurance)).status,200);assert.equal(writes.length,1);assert.equal(usage.length,1);assert.equal(writes[0].isInsured,true);
 assert.equal((await send('paperwork',{...insurance,section:'license',licenseStatus:'yes'})).status,400);
 const loc={requestId:randomUUID(),latitude:-33.9,longitude:18.4,locationText:'Workshop'};assert.equal((await send('location',loc)).status,403);
 allowed.add('location');for(const patch of [{latitude:null},{latitude:91},{longitude:181},{latitude:''},{gpsAccuracyMeters:-1}])assert.equal((await send('location',{...loc,...patch})).status,400);
 assert.equal((await send('location',loc)).status,200);assert.equal((await send('location',loc)).status,200);assert.equal(writes.length,2);assert.equal(usage.length,2);
 revoked=true;assert.equal((await send('location',{...loc,requestId:randomUUID()})).status,403);assert.equal(writes.length,2);
 revoked=false;origin=false;assert.equal((await send('paperwork',{...insurance,requestId:randomUUID()})).status,403);assert.equal(writes.length,2);
});
