'use client';
import {useEffect,useState} from 'react';
import styles from '../app/business/page.module.css';
type Listing={id:string;name:string;email:string;status:string;logo_data:string;details:{phone?:string;website?:string;town?:string;serviceArea?:string;services?:string[]}};
export default function AccountDirectoryListing({name='',phone='',emailVerified}:{name?:string;phone?:string;emailVerified:boolean}) {
 const [listing,setListing]=useState<Listing|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[failed,setFailed]=useState(false),[editing,setEditing]=useState(false),[logo,setLogo]=useState('');
 async function load(){setLoading(true);setFailed(false);try{const r=await fetch('/api/account-directory',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setListing(d.listing);setLogo(d.listing?.logo_data||'');}catch(e){setFailed(true);setNotice(e instanceof Error?e.message:'Unable to load listing.');}finally{setLoading(false);}}
 useEffect(()=>{if(emailVerified)void load();else setLoading(false);},[emailVerified]);
 async function save(body:Record<string,unknown>){setBusy(true);setNotice('');try{const r=await fetch('/api/account-directory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setListing(d.listing);setEditing(false);setNotice(body.action==='hide'?'Your listing is hidden.':'Request sent. Aim4price will review your listing.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 const status=listing?.status==='active'?'Listed':listing?.status==='invited'?'Pending review':'Not listed';
 return <section className={`${styles.panel} ${styles.directoryPanel}`} aria-labelledby="directory-listing-title">
  <div className={styles.directoryHeading}><div><h2 id="directory-listing-title">Directory listing</h2><p className={styles.muted}>Help asset owners find your business. A basic listing is free.</p></div><span className={listing?.status==='active'?styles.verifiedBadge:styles.pendingBadge}>{loading?'Loading…':failed?'Unavailable':status}</span></div>
  {!emailVerified?<p>Verify your email to request a listing.</p>:loading?<p>Loading your listing…</p>:failed?<button className={styles.secondaryButton} onClick={()=>void load()}>Try again</button>:editing?<form className={`${styles.form} ${styles.businessForm}`} onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void save({...data,accepted:data.accepted==='on',services:String(data.services||'').split(',').map(v=>v.trim()).filter(Boolean),logoData:logo});}}>
   <div className={styles.directoryLogo}><div>{logo?<img src={logo} alt="Business logo preview"/>:<span>Logo</span>}</div><label>Business logo · optional<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2000000||!['image/png','image/jpeg','image/webp'].includes(file.type)){setNotice('Choose a PNG, JPEG or WebP logo under 2 MB.');return;}setBusy(true);try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Unable to read logo.'));reader.readAsDataURL(file);});setLogo(data);setNotice('');}catch(e){setNotice(e instanceof Error?e.message:'Unable to read logo.');}finally{setBusy(false);}}}/><small>PNG, JPEG or WebP · up to 2 MB</small></label>{logo&&<button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>setLogo('')}>Remove</button>}</div>
   <label>Business name<input name="name" required maxLength={200} defaultValue={listing?.name||name}/></label>
   <label>Contact number<input name="phone" type="tel" required maxLength={40} defaultValue={listing?.details.phone||phone}/></label>
   <label>Town / city<input name="town" required maxLength={200} defaultValue={listing?.details.town||''}/></label>
   <label>Areas served<input name="serviceArea" maxLength={300} placeholder="For example: George and surrounding areas" defaultValue={listing?.details.serviceArea||''}/></label>
   <label>Services offered<input name="services" required maxLength={1000} placeholder="For example: Repairs, servicing, parts" defaultValue={listing?.details.services?.join(', ')||''}/></label>
   <label>Website · optional<input name="website" type="url" maxLength={500} placeholder="https://" defaultValue={listing?.details.website||''}/></label>
   <div className={styles.directoryConsent}><p>Your verified account email will be used for enquiries. New listings and changes are reviewed before publication.</p><label><input type="checkbox" name="accepted" required/> List my business and contact details in the Aim4price directory.</label><small>A listing does not grant access to assets or guarantee workmanship.</small></div>
   <div className={styles.formFooter}><button type="button" disabled={busy} className={styles.secondaryButton} onClick={()=>{setEditing(false);setLogo(listing?.logo_data||'');}}>Cancel</button><button className={styles.button} disabled={busy}>{busy?'Saving…':listing?'Submit for review':'Request listing'}</button></div>
  </form>:<div className={styles.directoryActions}>{listing?.logo_data&&<img src={listing.logo_data} alt={`${listing.name} logo`}/>}<p className={styles.muted}>{listing?.status==='invited'?'Your listing is waiting for Aim4price review.':listing?.status==='active'?'Owners can find your business in the directory.':'Choose to make your business visible to asset owners.'}</p><button className={styles.button} onClick={()=>setEditing(true)}>{listing?'Edit listing':'Request listing'}</button>{listing&&listing.status!=='paused'&&<button disabled={busy} className={styles.secondaryButton} onClick={()=>void save({action:'hide'})}>Hide listing</button>}</div>}
  {notice&&<p role="status" className={styles.notice}>{notice}</p>}
 </section>;
}
