-- Aim4price database note
--
-- This file is not the live source of truth for Railway.
-- Use the SQL files in database/migrations/ instead.
--
-- Current database direction: Option B (simple / practical)
--
-- Core live tables:
--   brands
--   sectors
--   equipment_families
--   equipment_models
--   equipment_model_aliases
--   market_vault_listings
--   valuation_runs
--   asset_register_items
--   tractor_catalog (temporary tractor bridge while tractors remain the first live family)
--
-- Core idea:
--   - replacement prices live directly on equipment_models
--   - depreciation logic lives in GitHub code
--   - generic fallback rows live inside equipment_models
--   - sectors are fixed to 1=agricultural, 2=industrial, 3=construction
--
-- Current migration order:
--   01-agri-foundation.sql
--   02-agri-seed-and-backfill.sql
--   03-agri-verify.sql
--   04-valuation-usability-and-model-candidate-constraint.sql
--   05-asset-register-marketplace-save-hardening.sql
--   06-asset-register-insurance-status.sql
--   07-asset-register-documents.sql
--   08-asset-register-brand-model-backfill.sql
--   09-account-profile-branding-and-marketplace-contact.sql
--   10-asset-register-license-status.sql
--   11-asset-register-license-registration.sql
--   12-fuel-ledger.sql
--   13-partner-access-and-leads.sql
--   14-account-profile-subtype.sql
--   15-account-role-split-and-partner-notes.sql
--   16-remove-shared-register-access.sql
--   17-owner-contact-requests.sql
--   18-asset-partner-note-pdf-attachments.sql
--   19-asset-register-manual-replacement-price.sql
--   20-multi-asset-registers.sql
--   21-asset-register-logos.sql
--   22-account-profile-business-media.sql
--   23-asset-register-upload-storage.sql
--   24-asset-register-upload-storage-repair.sql
--   25-asset-register-upload-file-bytes-compat.sql
--   26-users-page-request-controls-and-messages.sql
--   27-user-message-document-attachments.sql
--   28-aim4-four-sector-foundation.sql
--   29-manual-activation-and-introduced-by.sql
--   30-admin-only-access-hardening.sql
