-- Aim4price database note
--
-- This file is not the live source of truth for Railway.
-- Use the SQL files in database/migrations/ instead.
--
-- Current database direction: Option B (simple / practical)
--
-- Core live tables:
--   brands
--   sectors
--   equipment_families
--   equipment_models
--   equipment_model_aliases
--   market_vault_listings
--   valuation_runs
--   asset_register_items
--   tractor_catalog (temporary tractor bridge while tractors remain the first live family)
--
-- Core idea:
--   - replacement prices live directly on equipment_models
--   - depreciation logic lives in GitHub code
--   - generic fallback rows live inside equipment_models
--   - sectors are fixed to 1=agricultural, 2=industrial, 3=construction
--
-- Current migration order:
--   01-agri-foundation.sql
--   02-agri-seed-and-backfill.sql
--   03-agri-verify.sql
--   04-valuation-usability-and-model-candidate-constraint.sql
--   05-asset-register-marketplace-save-hardening.sql
