'use client';
import {useEffect,useState,useCallback,useId} from 'react';
import {label,display,matchesHistorySearch} from '../../lib/asset-history-presentation';
import {downloadCanonicalReportPdf} from '../../lib/report-open';
import {useRouter} from 'next/navigation';
import LeadActionDialog from '../leads/LeadActionDialog';
import {restorableChanges} from '../../lib/asset-history-fields';
import type {HistoryItem} from '../../lib/asset-history';
import styles from './AssetHistoryDialog.module.css';
import buttons from '../../app/asset-register/page.module.css';
const categories=['all','details','values','costs','fuel','budgets','maintenance','documents'];
export default function AssetHistoryDialog({endpoint,assetTitle,assetSubtitle,onClose,onSaved}:{endpoint:string;assetTitle:string;assetSubtitle?:string;onClose:()=>void;onSaved?:()=>void}){
 const historyId=useId();
 const router=useRouter(),[items,setItems]=useState<HistoryItem[]>([]),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<HistoryItem|null>(null),[notice,setNotice]=useState('');
 const [valuePreview,setValuePreview]=useState<{currentValue:number;previousValue:number;manual:boolean;revision:string}|null>(null);
 async function chooseRestore(item:HistoryItem){setError('');setNotice('');setValuePreview(null);if(!item.valueRestorable){setConfirm(item);return;}setBusy(true);try{const r=await fetch(`${endpoint}/history`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:item.id,action:'previewValueRestore'})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not load the previous value.');setValuePreview(d);setConfirm(item);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 const load=useCallback(async(cursor?:string,signal?:AbortSignal)=>{setBusy(true);setError('');try{const q=new URLSearchParams();if(category!=='all')q.set('category',category);if(cursor)q.set('before',cursor);const r=await fetch(`${endpoint}/history?${q}`,{cache:'no-store',signal}),d=await r.json();if(!r.ok)throw Error(d.error||'History could not be loaded.');setItems(prev=>cursor?[...prev,...d.items]:d.items);setNext(d.nextBefore||null);}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Please try again.');}finally{if(!signal?.aborted)setBusy(false);}},[endpoint,category]);
 useEffect(()=>{const controller=new AbortController();void load(undefined,controller.signal);return()=>controller.abort();},[load]);
 async function restore(){if(!confirm)return;setBusy(true);setError('');try{const r=await fetch(`${endpoint}/history`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:confirm.id,confirmed:true,...(valuePreview?{action:"restoreValue",revision:valuePreview.revision,expectedValue:valuePreview.previousValue}:{})})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not restore this change.');setConfirm(null);setNotice(valuePreview?'Previous value restored. The change is recorded in history.':'Change retracted. The original entry and this correction stay in history.');await load();router.refresh();window.dispatchEvent(new CustomEvent('aim4price:asset-register-updated'));onSaved?.();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 const query=search.trim().toLocaleLowerCase();
 const visibleItems=items.filter(item=>matchesHistorySearch(item,query));
 const [downloading,setDownloading]=useState(false);
 async function downloadReport(){setDownloading(true);setError('');try{const params=new URLSearchParams({format:'pdf'});if(category!=='all')params.set('category',category);if(query)params.set('search',query);await downloadCanonicalReportPdf(`${endpoint}/history?${params}`);}catch(e){setError(e instanceof Error?e.message:'The report could not be downloaded.');}finally{setDownloading(false);}}

 return <LeadActionDialog title="Asset history" assetTitle={assetTitle} assetSubtitle={assetSubtitle} onClose={onClose} busy={busy} className={styles.dialog} footer={!confirm?<div className={styles.reportFooter}><button type="button" className={styles.downloadButton} disabled={busy||downloading} onClick={()=>void downloadReport()}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m-4-4 4 4 4-4M5 16v4h14v-4"/></svg>{downloading?'Preparing PDF…':'Download PDF'}</button></div>:undefined}>
 {!confirm&&<div className={styles.toolbar}><div className={styles.search}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/></svg><input aria-label="Search history" type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search history…" /></div><div className={styles.filters} role="group" aria-label="History category">{categories.map(value=><button key={value} type="button" aria-pressed={category===value} onClick={()=>{setConfirm(null);setCategory(value);}}>{value==='all'?'All':label(value)}</button>)}</div></div>}
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {confirm?<section className={styles.confirm}><strong className={styles.confirmTitle}>{valuePreview?'Restore previous value?':'Retract this change?'}</strong>{valuePreview?<><div className={styles.restoreValues}><div><span>Current value</span><strong>R {display(valuePreview.currentValue,'value')}</strong></div><span aria-hidden="true">→</span><div><span>Restore to</span><strong>R {display(valuePreview.previousValue,'value')}</strong></div></div><p className={styles.hint}>Excluding VAT. {valuePreview.manual?'Your manual value will be restored.':'Automatic depreciation continues from the previous valuation.'}</p></>:<p>Restore the previous details below? Newer edits are protected.</p>}<dl className={styles.changes} hidden={!!valuePreview}>{restorableChanges(confirm.before,confirm.after).map(key=><div key={key}><dt>{label(key)}</dt><dd><span className={styles.before}>{display(confirm.after[key],key)}</span><span className={styles.arrow} aria-label="restore to">→</span><strong>{display(confirm.before[key],key)}</strong></dd></div>)}</dl><p className={styles.hint}>Both the original change and this correction stay in history.</p><div className={styles.actions}><button className={buttons.secondaryButton} disabled={busy} onClick={()=>setConfirm(null)}>{'Cancel'}</button><button className={buttons.primaryButton} disabled={busy} onClick={()=>void restore()}>{valuePreview?'Restore':'Retract'}</button></div></section>:null}
 {!confirm&&<div className={styles.list} role="region" aria-label="History entries" tabIndex={0}>{!visibleItems.length&&!busy&&<p className={styles.empty}>{query?'No matching activity in the loaded history.':'No recorded activity in this category.'}</p>}{visibleItems.map(item=><details name={historyId} className={styles.event} key={`${category}-${query}-${item.id}`}><summary className={styles.heading}><span className={styles.summaryCopy}><strong>{item.action}</strong><span className={styles.meta}>{item.actorName}</span></span><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString('en-ZA',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</time><svg className={styles.chevron} viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></summary><div className={styles.expanded}><dl className={styles.changes}>{Object.keys({...item.before,...item.after}).map(key=><div key={key}><dt>{label(key)}</dt><dd>{key in item.before&&<><span className={styles.before}>{display(item.before[key],key)}</span><span className={styles.arrow} aria-label="changed to">→</span></>}<strong>{key in item.after?display(item.after[key],key):'—'}</strong></dd></div>)}</dl><div className={styles.actions}>{!item.valueRestorable&&item.href&&['values','costs','fuel','budgets'].includes(item.category)&&<a className={buttons.secondaryButton} href={item.href}>{item.category==='values'?'Review':item.category==='costs'||item.category==='fuel'||item.category==='budgets'?'Open':'Open'}</a>}{(item.restorable||item.valueRestorable)&&<button className={`${buttons.secondaryButton} ${styles.retract}`} disabled={busy} onClick={()=>void chooseRestore(item)}>{item.valueRestorable?'Restore':'Retract'}</button>}</div></div></details>)}{next&&<div className={styles.loadMore}>{query&&<p className={styles.hint}>Search covers loaded entries. Load earlier activity to search further back.</p>}<button className={buttons.secondaryButton} disabled={busy} onClick={()=>void load(next)}>Load more</button></div>}</div>}

 {busy&&<p role="status">Loading…</p>}
 </LeadActionDialog>;
}
