'use client';
import {useEffect,useState,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import LeadActionDialog from '../leads/LeadActionDialog';
import styles from './AssetValueDialog.module.css';
import assetStyles from '../../app/asset-register/page.module.css';
const money=(v:unknown)=>v===null||v===undefined?'Not saved':new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(v));
type RequestItem={id:string;amount:number|string;reason:string;actor_name:string;status:string;submitted_value:number|string;created_at:string;email_sent_at?:string;email_error?:string};
type Review={asset:{id:string;title:string;value:number;replacementPrice:number|null;revision:string;manual:boolean;baseline?:{amount:number;actorName:string;date:string;reason:string}|null};requests:RequestItem[];history:Array<{id:string;action:string;actor_name:string;created_at:string;before_data:{amount:number};after_data:{amount:number;reason:string}}>};
export default function AssetValueDialog({endpoint,assetTitle,onClose,onSaved,suggest=false,initialReplacement,legacyCorrectionId}: {endpoint:string;assetTitle:string;onClose:()=>void;onSaved?:(item?:any)=>void;suggest?:boolean;initialReplacement?:number;legacyCorrectionId?:string}) {
 const router=useRouter();const [review,setReview]=useState<Review|null>(null),[current,setCurrent]=useState<number|null>(null),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [view,setView]=useState<'menu'|'override'|'replacement'|'review'|'history'>(initialReplacement?'replacement':'menu'),[selected,setSelected]=useState<RequestItem|null>(null),[replacement,setReplacement]=useState(String(initialReplacement??'')),[preview,setPreview]=useState<{revision:string;currentValue:number;recalculatedValue:number|null}|null>(null);
 const [requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const refresh=useCallback(async()=>{const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(suggest)setCurrent(d.value);else setReview(d);},[endpoint,suggest]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[refresh]);
 function changed(){setRequestId(crypto.randomUUID());setNotice('');}
 async function send(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{
  if(action!=='previewReplacement'&&reason.trim().length<3)throw Error('Please give a short reason.');
  if((action==='suggest'||action==='override')&&!amount.trim())throw Error('Enter a value excluding VAT.');
  const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,amount:Number(amount),reason,requestId,legacyCorrectionId,revision:preview?.revision||review?.asset.revision,...extra})});const d=await r.json();if(!r.ok)throw Error(d.error);
  if(action==='previewReplacement'){setPreview(d);return;}
  setNotice(suggest?'Suggestion sent. The owner must approve it before the asset value changes.':'Saved. The change has been recorded in asset history.');setRequestId(crypto.randomUUID());setReason('');setAmount('');setView('menu');setSelected(null);setPreview(null);await refresh();router.refresh();onSaved?.(d.item);
 }catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 function open(next:typeof view){setView(next);setReason('');setError('');setNotice('');setPreview(null);changed();}
 const pending=review?.requests.filter(r=>r.status==='pending')||[];
 return <LeadActionDialog title={suggest?'Suggest current value':'Asset values'} assetTitle={assetTitle} onClose={onClose} busy={busy} className={`${styles.dialog} ${suggest?styles.suggestionDialog:''}`} footer={suggest?<div className={styles.suggestionFooter}><button type="button" className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Reload latest values</button><button type="button" className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('suggest')}>{busy?'Sending…':'Send suggestion'}</button></div>:undefined}>
 <div className={styles.body}>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!suggest&&<div className={styles.summary}><div><span>Current value · excl. VAT</span><strong>{money(suggest?current:review?.asset.value)}</strong></div>{!suggest&&<div><span>Replacement price · excl. VAT</span><strong>{money(review?.asset.replacementPrice)}</strong></div>}</div>}
 {!suggest&&view!=='menu'&&<div className={styles.actions}><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>open('menu')}>Back to values</button></div>}
 {!suggest&&!review&&!error&&<p>Loading values…</p>}
 {!suggest&&review&&view==='menu'&&<><div className={styles.actions}><button className={assetStyles.primaryButton} onClick={()=>open('override')}>Override current value</button><button className={assetStyles.secondaryButton} onClick={()=>{setReplacement(String(review.asset.replacementPrice??''));open('replacement')}}>Change replacement price</button><button className={assetStyles.secondaryButton} onClick={()=>open('history')}>History</button></div>
 {review.asset.baseline&&<p className={styles.note}>Last approved starting value: {money(review.asset.baseline.amount)} by {review.asset.baseline.actorName} on {new Date(review.asset.baseline.date).toLocaleDateString('en-ZA')}.</p>}
 {pending.length>0?<><strong>Value suggestions awaiting review</strong>{pending.map(r=><div className={styles.request} key={r.id}><strong>{money(r.amount)} · {r.actor_name}</strong><p>{r.reason}</p>{r.email_error&&<small>Email unavailable; this suggestion remains available for review here.</small>}<button className={assetStyles.primaryButton} onClick={()=>{open('review');setSelected(r)}}>Review suggestion</button></div>)}</>:<p className={styles.note}>No value suggestions awaiting review.</p>}</>}
 {suggest&&<>
  <div className={styles.suggestionValues}>
   <div className={styles.currentValue}><span>Current value · excl. VAT</span><strong>{money(current).replace(/[,\s]/g,' ')}</strong></div>
   <label className={styles.proposedValue}><span>Suggested value · excl. VAT</span><div className={styles.currencyInput}><span aria-hidden="true">R</span><input aria-label="Suggested current value excluding VAT" type="number" min="0" max="1000000000000" value={amount} disabled={busy} placeholder="Enter amount" onChange={e=>{setAmount(e.target.value);changed()}}/></div></label>
  </div>
  <label className={`${styles.field} ${styles.suggestionReason}`}><span>Reason for this value</span><textarea maxLength={1500} rows={3} value={reason} disabled={busy} placeholder="For example: recent inspection, condition or comparable equipment." onChange={e=>{setReason(e.target.value);changed()}}/></label>
  <p className={`${styles.note} ${styles.approvalNote}`}>The owner must approve your suggestion before the current value changes.</p>
 </>}
 {(!suggest&&view==='override')&&<><div className={styles.fields}><label className={styles.field}>New current value · excl. VAT<input type="number" min="0" max="1000000000000" value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);changed()}}/></label><label className={styles.field}>Reason<textarea maxLength={1500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label></div><p className={styles.note}>{suggest?'This is an estimate for the owner to review. It will not change the live value until approved.':review?.asset.manual?'This is a manual value. Automatic depreciation needs a supported Aim4price valuation first.':'This becomes the starting value for future depreciation. Past depreciation will not be applied again.'}</p><button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send(suggest?'suggest':'override')}>{busy?'Saving…':suggest?'Send suggestion':'Confirm override'}</button></>}
 {!suggest&&view==='review'&&selected&&<><div className={styles.request}><strong>{selected.actor_name} suggested {money(selected.amount)}</strong><p>{selected.reason}</p><small>Value when submitted: {money(selected.submitted_value)}. The current value above is the latest saved value.</small></div><label className={styles.field}>Decision reason<textarea value={reason} maxLength={1500} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label><p className={styles.note}>{review?.asset.manual?'Approval updates the manual value.':'Approval sets a new starting value. Automatic depreciation continues from it.'}</p><div className={styles.actions}><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('decline',{proposalId:selected.id})}>Decline</button><button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('approve',{proposalId:selected.id})}>Approve value</button></div></>}
 {!suggest&&view==='replacement'&&<><div className={styles.fields}><label className={styles.field}>New replacement price · excl. VAT<input type="number" min="1" value={replacement} disabled={busy} onChange={e=>{setReplacement(e.target.value);setPreview(null);changed()}}/></label><label className={styles.field}>Reason<textarea maxLength={1500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label></div><p className={styles.note}>A higher or lower replacement price can change current value. Keep current value preserves today's amount; subsequent depreciation continues for Aim4price-valued assets.</p>{!preview?<button className={assetStyles.primaryButton} disabled={busy||!replacement.trim()} onClick={()=>void send('previewReplacement',{replacementPrice:Number(replacement)})}>Preview change</button>:<><p>Recalculated current value: <strong>{preview.recalculatedValue===null?'Manual value — use Override':money(preview.recalculatedValue)}</strong></p><div className={styles.actions}><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('replacement',{replacementPrice:Number(replacement),mode:'keep'})}>Keep current value</button><button className={assetStyles.primaryButton} disabled={busy||preview.recalculatedValue===null} onClick={()=>void send('replacement',{replacementPrice:Number(replacement),mode:'recalculate'})}>Recalculate current value</button></div></>}</>}
 {!suggest&&view==='history'&&<div className={styles.history}>{review?.history.map(h=><div className={styles.request} key={h.id}><strong>{h.action} · {h.actor_name}</strong><p>{money(h.before_data.amount)} → {money(h.after_data.amount)}</p><p>{h.after_data.reason}</p><small>{new Date(h.created_at).toLocaleString('en-ZA')}</small></div>)}{review?.requests.filter(r=>r.status!=='pending').map(r=><div className={styles.request} key={r.id}><strong>{r.status} · {money(r.amount)} · {r.actor_name}</strong><p>{r.reason}</p></div>)}{!review?.history.length&&!review?.requests.some(r=>r.status!=='pending')&&<p>No value decisions yet.</p>}</div>}
 {!suggest&&<button type="button" className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void refresh().then(()=>{setPreview(null);setError('')}).catch(e=>setError(e.message))}>Reload latest values</button>}
 </div></LeadActionDialog>;
}
