'use client';
import {useEffect,useState,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import LeadActionDialog from '../leads/LeadActionDialog';
import ModalSelect from '../AssetModalSelect';
import {restorableChanges} from '../../lib/asset-history-fields';
import type {HistoryItem} from '../../lib/asset-history';
import styles from './AssetHistoryDialog.module.css';
import buttons from '../../app/asset-register/page.module.css';
const categories=['all','details','values','costs','fuel','budgets','maintenance','documents'];
const friendly:Record<string,string>={value:'Current value · excl. VAT',selected_value_ex_vat:'Current value · excl. VAT',replacement_price_ex_vat:'Replacement price · excl. VAT',issue_noted_at:'Problem resolved',hours:'Usage',life_worked_percent:'Life worked · %',year_model:'Year model'};
const label=(s:string)=>friendly[s]||s.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).replace('Ex Vat','· excl. VAT');
const display=(value:unknown,key?:string)=>value==null?'Not saved':typeof value==='boolean'?(value?'Yes':'No'):typeof value==='object'?JSON.stringify(value):typeof value==='number'&&key!=='year_model'?value.toLocaleString('en-ZA').replace(/,/g,' '):String(value);
export default function AssetHistoryDialog({endpoint,assetTitle,assetSubtitle,onClose,onSaved}:{endpoint:string;assetTitle:string;assetSubtitle?:string;onClose:()=>void;onSaved?:()=>void}){
 const router=useRouter(),[items,setItems]=useState<HistoryItem[]>([]),[category,setCategory]=useState('all'),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<HistoryItem|null>(null),[notice,setNotice]=useState('');
 const load=useCallback(async(cursor?:string,signal?:AbortSignal)=>{setBusy(true);setError('');try{const q=new URLSearchParams();if(category!=='all')q.set('category',category);if(cursor)q.set('before',cursor);const r=await fetch(`${endpoint}/history?${q}`,{cache:'no-store',signal}),d=await r.json();if(!r.ok)throw Error(d.error||'History could not be loaded.');setItems(prev=>cursor?[...prev,...d.items]:d.items);setNext(d.nextBefore||null);}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Please try again.');}finally{if(!signal?.aborted)setBusy(false);}},[endpoint,category]);
 useEffect(()=>{const controller=new AbortController();void load(undefined,controller.signal);return()=>controller.abort();},[load]);
 async function restore(){if(!confirm)return;setBusy(true);setError('');try{const r=await fetch(`${endpoint}/history`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:confirm.id,confirmed:true})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not restore this change.');setConfirm(null);setNotice('Change retracted. The original entry and this correction stay in history.');await load();router.refresh();window.dispatchEvent(new CustomEvent('aim4price:asset-register-updated'));onSaved?.();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <LeadActionDialog title="Asset history" assetTitle={assetTitle} assetSubtitle={assetSubtitle} onClose={onClose} busy={busy} className={styles.dialog}>
 <div className={styles.toolbar}><ModalSelect label="History category" buttonLabel="History category" value={category} options={categories.map(value=>({value,label:value==='all'?'All activity':label(value)}))} onChange={value=>{setConfirm(null);setCategory(value);}}/><p>Your asset’s activity, with a record of every correction.</p></div>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {confirm?<section className={styles.confirm}><strong className={styles.confirmTitle}>Retract this change?</strong><p>The listed details will return to their previous values. Newer edits are protected.</p><div className={styles.columns}><span>Detail</span><span>Recorded value</span><span>Restore to</span></div><dl className={styles.changes}>{restorableChanges(confirm.before,confirm.after).map(key=><div key={key}><dt>{label(key)}</dt><dd className={styles.before}>{display(confirm.after[key],key)}</dd><dd>{display(confirm.before[key],key)}</dd></div>)}</dl><p className={styles.hint}>The original entry stays in history. Costs, fuel and maintenance records remain unchanged.</p><div className={styles.actions}><button className={buttons.secondaryButton} disabled={busy} onClick={()=>setConfirm(null)}>Keep change</button><button className={buttons.primaryButton} disabled={busy} onClick={()=>void restore()}>Confirm retraction</button></div></section>:null}
 {!confirm&&<div className={styles.list}>{!items.length&&!busy&&<p className={styles.empty}>No recorded activity in this category.</p>}{items.map(item=><article className={styles.event} key={item.id}><div className={styles.heading}><div><span className={styles.badge}>{label(item.category)}</span><strong>{item.action}</strong></div><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString('en-ZA',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div><p className={styles.meta}>{item.actorName} · {item.source}</p><div className={styles.columns}><span>Detail</span><span>Previous</span><span>Updated</span></div><dl className={styles.changes}>{Object.keys({...item.before,...item.after}).map(key=><div key={key}><dt>{label(key)}</dt><dd className={styles.before}>{key in item.before?display(item.before[key],key):'—'}</dd><dd>{key in item.after?display(item.after[key],key):'—'}</dd></div>)}</dl><div className={styles.actions}>{item.href&&<a className={buttons.secondaryButton} href={item.href}>{item.category==='values'?'Review values':item.category==='costs'||item.category==='fuel'||item.category==='budgets'?'Open record':'Open asset'}</a>}{item.restorable&&<button className={`${buttons.secondaryButton} ${styles.retract}`} disabled={busy} onClick={()=>{setConfirm(item);setError('');setNotice('');}}>Retract change</button>}</div></article>)}</div>}

 {busy&&<p role="status">Loading…</p>}{next&&!confirm&&<button className={buttons.secondaryButton} disabled={busy} onClick={()=>void load(next)}>Load earlier activity</button>}
 </LeadActionDialog>;
}
