'use client';
import {useEffect,useState,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import ModalSelect from '../AssetModalSelect';
import {pricingVatAmount,pricingInputExVat} from '../../lib/pricing-vat';
import LeadActionDialog from '../leads/LeadActionDialog';
import styles from './AssetValueDialog.module.css';
import assetStyles from '../../app/asset-register/page.module.css';
const money=(v:unknown)=>v===null||v===undefined?'Not saved':new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(v));
type RequestItem={id:string;amount:number|string;reason:string;actor_name:string;status:string;submitted_value:number|string;created_at:string;email_sent_at?:string;email_error?:string};
type Review={asset:{id:string;title:string;value:number;replacementPrice:number|null;revision:string;manual:boolean;baseline?:{amount:number;actorName:string;date:string;reason:string}|null};requests:RequestItem[];replacementRequests?:Array<{id:string;actorName:string;dealerName:string;reason?:string;proposedReplacementPriceExVat:number|null;email_error?:string|null}>;history:Array<{id:string;action:string;actor_name:string;created_at:string;before_data:{amount:number;replacementPrice?:number};after_data:{amount:number;reason:string;suggestionReason?:string}}>};
export default function AssetValueDialog({endpoint,assetTitle,onClose,onSaved,suggest=false,initialReplacement,legacyCorrectionId,initialView,replacementSuggestion}: {endpoint:string;assetTitle:string;onClose:()=>void;onSaved?:(item?:any)=>void;suggest?:boolean;initialReplacement?:number;legacyCorrectionId?:string;initialView?:'override'|'replacement';replacementSuggestion?:{readEndpoint:string;endpoint:string;sourceId:string;assetId?:string;current:number|null}}) {
 const router=useRouter();const [review,setReview]=useState<Review|null>(null),[current,setCurrent]=useState<number|null>(null),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [view,setView]=useState<'menu'|'override'|'replacement'|'review'|'history'|'reset'|'restore'>(initialView||(initialReplacement?'replacement':'menu')),[selected,setSelected]=useState<RequestItem|null>(null),[replacement,setReplacement]=useState(String(initialReplacement??'')),[preview,setPreview]=useState<{revision:string;currentValue:number;recalculatedValue:number|null}|null>(null);
 const [correctionId,setCorrectionId]=useState(legacyCorrectionId);
 const [manual,setManual]=useState(false),[sharedRevision,setSharedRevision]=useState(''),[restoreEntry,setRestoreEntry]=useState<Review['history'][number]|null>(null);
 const [suggestionVat,setSuggestionVat]=useState(false);
 const suggestedAmount=pricingInputExVat(Number(amount),suggestionVat);
 const [requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const refresh=useCallback(async()=>{if(replacementSuggestion){const r=await fetch(replacementSuggestion.readEndpoint,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not reload this asset.');setCurrent(d.asset.replacementPriceExVat);setManual(d.asset.manual===true);setSharedRevision(d.asset.revision||'');return;}const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(suggest){setCurrent(d.value);setManual(d.manual===true);setSharedRevision(d.revision||'');}else {setReview(d);if(initialView==='replacement'&&initialReplacement===undefined)setReplacement(String(d.asset.replacementPrice??''));}},[endpoint,suggest,replacementSuggestion]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[refresh]);
 function changed(){setRequestId(crypto.randomUUID());setNotice('');}
 async function send(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{
  if(!['previewReplacement','previewReset','retryNotification'].includes(action)&&reason.trim().length<3)throw Error('Please give a short reason.');
  if((action==='suggest'||action==='override')&&!amount.trim())throw Error('Enter a value excluding VAT.');
  if(replacementSuggestion){
   if(!Number.isFinite(Number(amount))||Number(amount)<=0)throw Error('Enter a replacement price greater than zero.');
   const link=!!replacementSuggestion.assetId;
   const r=await fetch(replacementSuggestion.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceType:link?'external':'lead',sourceId:replacementSuggestion.sourceId,assetId:replacementSuggestion.assetId,field:'replacementPriceExVat',value:suggestedAmount,reason,confirmed:true,revision:sharedRevision})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to send suggestion.');
   setNotice(d.correction?.status==='accepted'?'Manual replacement price saved. Current value is unchanged.':'Sent to the owner for approval.');await refresh();setAmount('');setReason('');router.refresh();onSaved?.();return;
  }
  const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,amount:suggest?suggestedAmount:Number(amount),reason,requestId,legacyCorrectionId:['replacement','declineReplacement'].includes(action)?correctionId:undefined,revision:preview?.revision||review?.asset.revision||sharedRevision,confirmed:true,expectedValue:preview?.recalculatedValue,...extra})});const d=await r.json();if(!r.ok)throw Error(d.error);
  if(action==='previewReplacement'||action==='previewReset'){setPreview(d);return;}
  setNotice(action==='retryNotification'?'Notification retry requested. The suggestion remains available here.':suggest?(d.direct?'Manual value updated. The change is recorded in history.':'Suggestion sent. The owner must approve it before the asset value changes.'):'Saved. The change has been recorded in asset history.');setRequestId(crypto.randomUUID());setReason('');setAmount('');setView('menu');setSelected(null);setPreview(null);setCorrectionId(undefined);await refresh();router.refresh();onSaved?.(d.item);
 }catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 function open(next:typeof view){setView(next);setReason('');setError('');setNotice('');setPreview(null);changed();}
 const replacementRequests=review?.replacementRequests||[];
 const replacementRequest=replacementRequests.find(r=>r.id===correctionId);
 const pending=review?.requests.filter(r=>r.status==='pending')||[];
 return <LeadActionDialog title={replacementSuggestion?(manual?'Update replacement price':'Suggest replacement price'):suggest?(manual?'Update manual value':'Suggest current value'):view==='override'?'Change current value':view==='replacement'?'Change replacement price':view==='history'?'Value history':view==='review'?'Review suggestion':view==='reset'?'Return to Aim4price value':view==='restore'?'Restore previous value':'Manage values'} assetTitle={assetTitle} onClose={onClose} busy={busy} className={`${styles.dialog} ${suggest?styles.suggestionDialog:''}`} footer={suggest?<div className={styles.suggestionFooter}><button type="button" className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Refresh values</button><button type="button" className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('suggest')}>{busy?'Saving…':manual?'Confirm update':'Send suggestion'}</button></div>:undefined}>
 <div className={styles.body}>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!suggest&&<div className={styles.summary}><div><span>Current value · excl. VAT</span><strong>{money(suggest?current:review?.asset.value)}</strong></div>{!suggest&&<div><span>Replacement price · excl. VAT</span><strong>{money(review?.asset.replacementPrice)}</strong></div>}</div>}
 {!suggest&&<nav className={styles.toolbar} aria-label="Value navigation">{view!=='menu'?<button type="button" className={styles.utilityButton} disabled={busy} onClick={()=>open('menu')}>← Back to values</button>:<span>Choose what you want to change</span>}<button type="button" className={styles.utilityButton} disabled={busy} onClick={()=>void refresh().then(()=>{setPreview(null);setError('')}).catch(e=>setError(e.message))}>Refresh values</button></nav>}
 {!suggest&&!review&&!error&&<p>Loading values…</p>}
 {!suggest&&review&&view==='menu'&&<><div className={styles.menuActions}><button className={assetStyles.primaryButton} onClick={()=>open('override')}>Change current value</button><button className={assetStyles.secondaryButton} onClick={()=>{setCorrectionId(undefined);setReplacement(String(review.asset.replacementPrice??''));open('replacement')}}>Change replacement price</button><button className={assetStyles.secondaryButton} onClick={()=>open('history')}>History</button>{!review.asset.manual&&review.asset.baseline&&<button className={assetStyles.secondaryButton} onClick={()=>open('reset')}>Return to Aim4price value</button>}</div>
 <p className={styles.note}>{review.asset.manual?'Manual value · editable with permission.':review.asset.baseline?'Aim4price depreciation · owner-approved starting value.':'Aim4price value · automatic depreciation.'}</p>{review.asset.baseline&&<p className={styles.note}>Last approved starting value: {money(review.asset.baseline.amount)} by {review.asset.baseline.actorName} on {new Date(review.asset.baseline.date).toLocaleDateString('en-ZA')}.</p>}
 {replacementRequests.map(r=><div className={styles.request} key={r.id}><strong>Replacement price: {money(r.proposedReplacementPriceExVat)} · {r.actorName||r.dealerName}</strong><p>{r.reason||'No reason supplied.'}</p>{r.email_error&&<><small>Email unavailable; review remains available here.</small><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('retryNotification',{notificationType:'replacement',notificationId:r.id})}>Retry notification</button></>}<button className={assetStyles.primaryButton} onClick={()=>{setCorrectionId(r.id);setReplacement(String(r.proposedReplacementPriceExVat??''));open('replacement');}}>Review replacement suggestion</button></div>)}{pending.length>0?<><div className={styles.reviewHeading}><strong>Suggestions to review</strong><p>Accept or decline a suggested value. Nothing changes until you approve it.</p></div>{pending.map(r=><div className={styles.request} key={r.id}><strong>{money(r.amount)} · {r.actor_name}</strong><p>{r.reason}</p>{r.email_error&&<><small>Email unavailable; this suggestion remains available for review here.</small><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('retryNotification',{notificationType:'current',notificationId:r.id})}>Retry notification</button></>}<button className={assetStyles.primaryButton} onClick={()=>{open('review');setSelected(r)}}>Review suggestion</button></div>)}</>:<p className={styles.note}>No current-value suggestions awaiting review.</p>}</>}
 {suggest&&<>
  <div className={styles.suggestionValues}>
   <div className={styles.currentValue}><span>{replacementSuggestion?'Replacement price':'Current value'} · excl. VAT</span><strong>{money(current).replace(/[,\s]/g,' ')}</strong></div>
   <label className={styles.proposedValue}><span>{manual?'New':'Suggested'} {replacementSuggestion?'replacement price':'value'}</span><div className={styles.suggestionInputRow}><ModalSelect label="Suggested value VAT" buttonLabel="Suggested value VAT" className={styles.vatSelect} value={suggestionVat?'included':'excluded'} options={[{value:'excluded',label:'Excl. VAT'},{value:'included',label:'Incl. VAT'}]} onChange={mode=>{const next=mode==='included';if(amount)setAmount(String(pricingVatAmount(suggestedAmount,next)));setSuggestionVat(next);}}/><div className={styles.currencyInput}><span aria-hidden="true">R</span><input aria-label="Suggested value" type="number" min="0" max="1000000000000" value={amount} disabled={busy} placeholder="Enter amount" onChange={e=>{setAmount(e.target.value);changed()}}/></div></div></label>
  </div>
  <label className={`${styles.field} ${styles.suggestionReason}`}><span>Reason for this value</span><textarea maxLength={1500} rows={3} value={reason} disabled={busy} placeholder="For example: recent inspection, condition or comparable equipment." onChange={e=>{setReason(e.target.value);changed()}}/></label>
  <p className={`${styles.note} ${styles.approvalNote}`}>{manual?(replacementSuggestion?'This manual asset’s replacement price will update immediately. Current value stays unchanged.':'You have permission to update this manual value. Confirming saves it immediately and records the change in history.'):(replacementSuggestion?'The owner must approve this price and choose its effect on current value.':'The owner must approve your suggestion before the current value changes.')}</p>
 </>}
 {(!suggest&&view==='override')&&<><div className={styles.fields}><label className={styles.field}>New current value · excl. VAT<input type="number" min="0" max="1000000000000" value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);changed()}}/></label><label className={styles.field}>Reason<textarea rows={2} placeholder="Why are you changing this value?" maxLength={1500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label></div><p className={styles.note}>{suggest?'This is an estimate for the owner to review. It will not change the live value until approved.':review?.asset.manual?'This is a manual value. Automatic depreciation needs a supported Aim4price valuation first.':'Automatic depreciation continues from this new value, starting today.'}</p><button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send(suggest?'suggest':'override')}>{busy?'Saving…':suggest?'Send suggestion':'Confirm value change'}</button></>}
 {!suggest&&view==='review'&&selected&&<><div className={styles.request}><strong>{selected.actor_name} suggested {money(selected.amount)}</strong><p>{selected.reason}</p><small>Value when submitted: {money(selected.submitted_value)}. The current value above is the latest saved value.</small></div><label className={styles.field}>Decision reason<textarea value={reason} maxLength={1500} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label><p className={styles.note}>{review?.asset.manual?'Approval updates the manual value.':'Approval sets a new starting value. Automatic depreciation continues from it.'}</p><div className={styles.actions}><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('decline',{proposalId:selected.id})}>Decline</button><button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('approve',{proposalId:selected.id})}>Approve value</button></div></>}
 {!suggest&&view==='replacement'&&<>{replacementRequest&&<div className={styles.request}><strong>{replacementRequest.actorName||replacementRequest.dealerName} suggested {money(replacementRequest.proposedReplacementPriceExVat)}</strong><p>{replacementRequest.reason||'No reason supplied.'}</p><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('declineReplacement')}>Decline suggestion</button></div>}<div className={styles.fields}><label className={styles.field}>New replacement price · excl. VAT<input type="number" min="1" value={replacement} disabled={busy} onChange={e=>{setReplacement(e.target.value);setPreview(null);changed()}}/></label><label className={styles.field}>Reason<textarea rows={2} placeholder="Why are you changing this value?" maxLength={1500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label></div><p className={styles.note}>Preview the change, then choose whether to keep or recalculate current value. Automatic depreciation continues for Aim4price-valued assets.</p>{!preview?<button className={assetStyles.primaryButton} disabled={busy||!replacement.trim()} onClick={()=>void send('previewReplacement',{replacementPrice:Number(replacement)})}>Preview change</button>:<><p>Current value before change: <strong>{money(preview.currentValue)}</strong></p><p>Recalculated current value: <strong>{preview.recalculatedValue===null?'Manual value — change it separately':money(preview.recalculatedValue)}</strong></p><div className={styles.actions}><button className={assetStyles.secondaryButton} disabled={busy} onClick={()=>void send('replacement',{replacementPrice:Number(replacement),mode:'keep'})}>Keep current value</button><button className={assetStyles.primaryButton} disabled={busy||preview.recalculatedValue===null} onClick={()=>void send('replacement',{replacementPrice:Number(replacement),mode:'recalculate'})}>Recalculate current value</button></div></>}</>}
 {!suggest&&view==='reset'&&<><p className={styles.note}>Remove the approved starting value and return to today’s Aim4price calculation. The previous decision stays in history.</p><label className={styles.field}>Reason<textarea value={reason} maxLength={1500} onChange={e=>{setReason(e.target.value);changed();}}/></label>{!preview?<button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('previewReset')}>Preview today’s value</button>:<><p>Current value: <strong>{money(preview.currentValue)}</strong> → Aim4price value: <strong>{money(preview.recalculatedValue)}</strong></p><button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('resetAim4price')}>Confirm return to Aim4price</button></>}</>}
 {!suggest&&view==='restore'&&restoreEntry&&<><p>Restore manual value to <strong>{money(restoreEntry.before_data.amount)}</strong>?</p><p className={styles.note}>This creates a new history entry. Replacement price stays unchanged.</p><label className={styles.field}>Reason<textarea value={reason} maxLength={1500} onChange={e=>{setReason(e.target.value);changed();}}/></label><button className={assetStyles.primaryButton} disabled={busy} onClick={()=>void send('restoreManual',{historyId:restoreEntry.id})}>Confirm restoration</button></>}
 {!suggest&&view==='history'&&<div className={styles.history}>{review?.history.map(h=><div className={styles.request} key={h.id}><strong>{h.action} · {h.actor_name}</strong><p>{money(h.before_data.amount)} → {money(h.after_data.amount)}</p><p>{h.after_data.reason}</p>{h.after_data.suggestionReason&&<p>Suggested reason: {h.after_data.suggestionReason}</p>}<small>{new Date(h.created_at).toLocaleString('en-ZA')}</small><div className={styles.actions}>{review.asset.manual&&typeof h.before_data.amount==='number'&&<button className={assetStyles.secondaryButton} onClick={()=>{setRestoreEntry(h);open('restore');}}>Restore previous manual value</button>}{typeof h.before_data.replacementPrice==='number'&&h.before_data.replacementPrice>0&&<button className={assetStyles.secondaryButton} onClick={()=>{setReplacement(String(h.before_data.replacementPrice));open('replacement');}}>Review previous replacement price</button>}</div></div>)}{review?.requests.filter(r=>r.status!=='pending').map(r=><div className={styles.request} key={r.id}><strong>{r.status} · {money(r.amount)} · {r.actor_name}</strong><p>{r.reason}</p></div>)}{!review?.history.length&&!review?.requests.some(r=>r.status!=='pending')&&<div className={styles.empty}><strong>No value changes yet</strong><p>Changes and decisions will appear here with who made them and why.</p></div>}</div>}

 </div></LeadActionDialog>;
}
