'use client';
import {useEffect,useState,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import LeadActionDialog from '../leads/LeadActionDialog';
import ModalSelect from '../AssetModalSelect';
import type {HistoryItem} from '../../lib/asset-history';
import styles from './AssetHistoryDialog.module.css';
import buttons from '../../app/asset-register/page.module.css';
const categories=['all','details','values','costs','fuel','budgets','maintenance','documents'];
const friendly:Record<string,string>={value:'Current value · excl. VAT',selected_value_ex_vat:'Current value · excl. VAT',replacement_price_ex_vat:'Replacement price · excl. VAT',issue_noted_at:'Problem resolved',hours:'Usage',year_model:'Year model'};
const label=(s:string)=>friendly[s]||s.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).replace('Ex Vat','· excl. VAT');
const display=(value:unknown)=>value==null?'Not saved':typeof value==='boolean'?(value?'Yes':'No'):typeof value==='object'?JSON.stringify(value):String(value);
export default function AssetHistoryDialog({endpoint,assetTitle,assetSubtitle,onClose,onSaved}:{endpoint:string;assetTitle:string;assetSubtitle?:string;onClose:()=>void;onSaved?:()=>void}){
 const router=useRouter(),[items,setItems]=useState<HistoryItem[]>([]),[category,setCategory]=useState('all'),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<HistoryItem|null>(null),[notice,setNotice]=useState('');
 const load=useCallback(async(cursor?:string,signal?:AbortSignal)=>{setBusy(true);setError('');try{const q=new URLSearchParams();if(category!=='all')q.set('category',category);if(cursor)q.set('before',cursor);const r=await fetch(`${endpoint}/history?${q}`,{cache:'no-store',signal}),d=await r.json();if(!r.ok)throw Error(d.error||'History could not be loaded.');setItems(prev=>cursor?[...prev,...d.items]:d.items);setNext(d.nextBefore||null);}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Please try again.');}finally{if(!signal?.aborted)setBusy(false);}},[endpoint,category]);
 useEffect(()=>{const controller=new AbortController();void load(undefined,controller.signal);return()=>controller.abort();},[load]);
 async function restore(){if(!confirm)return;setBusy(true);setError('');try{const r=await fetch(`${endpoint}/history`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:confirm.id,confirmed:true})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not restore this change.');setConfirm(null);setNotice('Restored. A new history entry records this correction.');await load();router.refresh();window.dispatchEvent(new CustomEvent('aim4price:asset-register-updated'));onSaved?.();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <LeadActionDialog title="Asset history" assetTitle={assetTitle} assetSubtitle={assetSubtitle} onClose={onClose} busy={busy} className={styles.dialog}>
 <div className={styles.toolbar}><ModalSelect label="History category" buttonLabel="History category" value={category} options={categories.map(value=>({value,label:value==='all'?'All activity':label(value)}))} onChange={value=>{setConfirm(null);setCategory(value);}}/><p>Changes and corrections stay in history. Includes new activity and previously recorded shared changes.</p></div>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {confirm?<section className={styles.confirm}><strong>Restore these previous details?</strong><p>Only the listed details will be restored. Newer edits will block the restoration.</p>{Object.entries(confirm.before).filter(([key])=>['title','year_model','condition','brand_name','model_name','note'].includes(key)).map(([key,value])=><p key={key}>{label(key)}: <strong>{display(value)}</strong></p>)}<div className={styles.actions}><button className={buttons.secondaryButton} disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button className={buttons.primaryButton} disabled={busy} onClick={()=>void restore()}>Confirm restoration</button></div></section>:null}
 {!confirm&&<div className={styles.list}>{!items.length&&!busy&&<p>No recorded activity in this category.</p>}{items.map(item=><article className={styles.event} key={item.id}><div className={styles.heading}><strong>{item.action}</strong><span>{label(item.category)}</span></div><p className={styles.meta}>{item.actorName} · {item.source} · {new Date(item.createdAt).toLocaleString('en-ZA')}</p><dl>{Object.keys({...item.before,...item.after}).map(key=><div key={key}><dt>{label(key)}</dt><dd>{key in item.before&&<><span className={styles.before}>{display(item.before[key])}</span><span aria-label="changed to"> → </span></>}{display(item.after[key])}</dd></div>)}</dl><div className={styles.actions}>{item.restorable&&<button className={buttons.secondaryButton} disabled={busy} onClick={()=>{setConfirm(item);setError('');}}>Restore previous details</button>}{item.href&&<a className={buttons.secondaryButton} href={item.href}>{item.category==='values'?'Review values':item.category==='costs'||item.category==='fuel'||item.category==='budgets'?'Open record':'Open asset'}</a>}</div></article>)}</div>}
 {busy&&<p role="status">Loading…</p>}{next&&<button className={buttons.secondaryButton} disabled={busy} onClick={()=>void load(next)}>Load earlier activity</button>}
 </LeadActionDialog>;
}
