import { AIM4PRICE_EMAIL_FONT_STACK, buildEmailBrandHeader } from './email-brand';
const escape = (value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function buildAccessEmail(input:{code?:string;url?:string;origin:string}) {
 const guest=Boolean(input.code),title=guest?'Your guest sign-in code':'Verify your email';
 const message=guest?'Use this code to open enquiries shared with your email.':'Confirm your email to access enquiries shared with you.';
 const action=guest?`<div style="font-size:32px;letter-spacing:8px;font-weight:700;padding:22px;background:#edf5ef;border-radius:10px;text-align:center;">${escape(input.code!)}</div>`:`<a href="${escape(input.url!)}" style="display:inline-block;padding:15px 24px;border-radius:9px;background:#19664d;color:#fff;text-decoration:none;font-weight:700;">Verify email</a>`;
 const note=guest?'This code expires in 10 minutes. Guest access has no personal Aim4price inbox, saved history or backup service.':'Return to your enquiry after verification. You only receive access to information shared with you.';
 return {subject:guest?'Your Aim4price guest sign-in code':'Verify your Aim4price email',text:`${title}\n${message}\n${input.code||input.url}\n${note}\nIf you did not request this, ignore this email.`,html:`<!doctype html><html><body style="margin:0;background:#f3f6f4;font-family:${AIM4PRICE_EMAIL_FONT_STACK};color:#173c32;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:24px 12px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;margin:auto;background:#fff;border:1px solid #dce7df;border-radius:12px;">${buildEmailBrandHeader(input.origin+'/brand/aim4price-mark-black.png')}<tr><td style="padding:30px;"><h1 style="font-size:24px;margin:0 0 16px;">${title}</h1><p style="line-height:1.7;color:#61756a;">${message}</p>${action}<p style="font-size:13px;line-height:1.7;color:#61756a;">${note}</p><p style="font-size:12px;line-height:1.6;color:#61756a;">If you did not request this, ignore this email.</p></td></tr></table></td></tr></table></body></html>`};
}
