/** Basic-only v1 planning assumptions; immutable once released. See BASIC-USAGE-PROFILES.md. */
export const BASIC_USAGE_PROFILE_VERSION = 'basic_usage_20260907_v1';
export type BasicUsageMetric = 'hours' | 'km' | 'percent';
export type BasicUsageProfile = {
  version: string;
  sectorKey: string;
  familyKey: string;
  primaryMetric: BasicUsageMetric;
  expectedLifetime: number;
  lifetimeUnit: 'hours' | 'km' | 'years';
  confidence: 'low' | 'medium';
  basis: 'existing' | 'planning' | 'toyota' | 'ashrae_context';
  percentageFallback: true;
};

// Exact reviewed catalogue membership: sector, family key, label, primary input, lifetime, basis.
// Percent rows carry a reference life in YEARS, never a fictitious meter reading.
export const BASIC_USAGE_FAMILIES: ReadonlyArray<readonly [string, string, string, BasicUsageMetric, number, BasicUsageProfile['basis']]> = [
  ["agricultural", "compact_tractor", "Compact Tractor", "hours", 8000, "existing"],
  ["agricultural", "orchard_vineyard_tractor", "Orchard & Vineyard Tractor", "hours", 10000, "existing"],
  ["agricultural", "small_field_tractor", "Small Field Tractor", "hours", 12000, "existing"],
  ["agricultural", "big_field_tractor", "Big Field Tractor", "hours", 14000, "existing"],
  ["agricultural", "articulated_tractor", "Articulated Tractor", "hours", 14000, "existing"],
  ["agricultural", "small_combine_harvester", "Small Combine Harvester", "hours", 8000, "existing"],
  ["agricultural", "medium_combine_harvester", "Medium Combine Harvester", "hours", 8000, "existing"],
  ["agricultural", "large_combine_harvester", "Large Combine Harvester", "hours", 8000, "existing"],
  ["agricultural", "self_propelled_forage_harvester", "Self-Propelled Forage Harvester", "hours", 8000, "existing"],
  ["agricultural", "mounted_tractor_forage_harvester", "Mounted Forage Harvester", "percent", 15, "planning"],
  ["agricultural", "trailed_tractor_forage_harvester", "Trailed Forage Harvester", "percent", 15, "planning"],
  ["agricultural", "cotton_harvester", "Cotton Harvester", "hours", 8000, "existing"],
  ["agricultural", "sugar_cane_harvester", "Sugar Cane Harvester", "hours", 8000, "existing"],
  ["agricultural", "cane_loader", "Cane Loader", "hours", 10000, "existing"],
  ["agricultural", "self_propelled_grape_harvester", "Grape Harvester", "hours", 8000, "existing"],
  ["agricultural", "mounted_tractor_tree_shaker", "Mounted Tree Shaker", "percent", 15, "planning"],
  ["agricultural", "trailed_tractor_tree_shaker", "Trailed Tree Shaker", "percent", 15, "planning"],
  ["agricultural", "trailed_nut_harvester", "Tractor-Drawn Nut Harvester", "percent", 15, "planning"],
  ["agricultural", "self_propelled_nut_harvester", "Self-Propelled Nut Harvester", "hours", 8000, "existing"],
  ["agricultural", "potato_digger", "Potato Digger", "percent", 15, "planning"],
  ["agricultural", "trailed_potato_harvester", "Potato Harvester", "percent", 15, "planning"],
  ["agricultural", "onion_lifter", "Onion Lifter & Windrower", "percent", 15, "planning"],
  ["agricultural", "onion_harvester", "Onion Harvester", "percent", 15, "planning"],
  ["agricultural", "tractor_root_crop_harvester", "Root Crop Harvester", "percent", 15, "planning"],
  ["agricultural", "crop_haulm_topper", "Potato & Onion Topper", "percent", 15, "planning"],
  ["agricultural", "groundnut_digger", "Groundnut Digger", "percent", 15, "planning"],
  ["agricultural", "bean_groundnut_pickup_harvester", "Bean & Groundnut Harvester", "percent", 15, "planning"],
  ["agricultural", "bean_puller", "Bean Puller & Windrower", "percent", 15, "planning"],
  ["agricultural", "grain_cutting_header", "Grain Cutting Header", "percent", 15, "planning"],
  ["agricultural", "maize_header", "Maize Header", "percent", 15, "planning"],
  ["agricultural", "sunflower_header", "Sunflower Header", "percent", 15, "planning"],
  ["agricultural", "combine_pickup_header", "Combine Pickup Header", "percent", 15, "planning"],
  ["agricultural", "forage_crop_cutting_header", "Forage Crop Cutting Header", "percent", 15, "planning"],
  ["agricultural", "forage_pickup_header", "Forage Pickup Header", "percent", 15, "planning"],
  ["agricultural", "self_propelled_windrower", "Swather / Windrower", "hours", 8000, "existing"],
  ["agricultural", "mounted_hay_mower", "Mounted Hay Mower", "percent", 15, "planning"],
  ["agricultural", "mounted_mower_conditioner", "Mounted Mower Conditioner", "percent", 15, "planning"],
  ["agricultural", "trailed_hay_mower", "Trailed Hay Mower", "percent", 15, "planning"],
  ["agricultural", "trailed_mower_conditioner", "Trailed Mower Conditioner", "percent", 15, "planning"],
  ["agricultural", "hay_rake", "Hay Rake", "percent", 15, "planning"],
  ["agricultural", "hay_tedder", "Hay Tedder", "percent", 15, "planning"],
  ["agricultural", "round_baler", "Round Baler", "percent", 15, "planning"],
  ["agricultural", "small_square_baler", "Small Square Baler", "percent", 15, "planning"],
  ["agricultural", "large_square_baler", "Large Square Baler", "percent", 15, "planning"],
  ["agricultural", "baler_wrapper", "Baler & Wrapper Combination", "percent", 15, "planning"],
  ["agricultural", "bale_wrapper", "Bale Wrapper", "percent", 15, "planning"],
  ["agricultural", "bale_handler", "Bale Handler", "percent", 15, "planning"],
  ["agricultural", "bale_shredder", "Bale Shredder", "percent", 15, "planning"],
  ["agricultural", "bale_unroller", "Bale Unroller", "percent", 15, "planning"],
  ["agricultural", "mounted_row_crop_planter", "Mounted Row Crop Planter", "percent", 15, "planning"],
  ["agricultural", "trailed_row_crop_planter", "Trailed Row Crop Planter", "percent", 15, "planning"],
  ["agricultural", "mounted_seed_drill", "Mounted Seed Drill", "percent", 15, "planning"],
  ["agricultural", "trailed_seed_drill", "Trailed Seed Drill", "percent", 15, "planning"],
  ["agricultural", "mounted_vegetable_seed_planter", "Mounted Vegetable Seed Planter", "percent", 15, "planning"],
  ["agricultural", "trailed_vegetable_seed_planter", "Trailed Vegetable Seed Planter", "percent", 15, "planning"],
  ["agricultural", "mounted_seedling_transplanter", "Mounted Seedling Transplanter", "percent", 15, "planning"],
  ["agricultural", "trailed_seedling_transplanter", "Trailed Seedling Transplanter", "percent", 15, "planning"],
  ["agricultural", "mounted_potato_planter", "Mounted Potato Planter", "percent", 15, "planning"],
  ["agricultural", "trailed_potato_planter", "Trailed Potato Planter", "percent", 15, "planning"],
  ["agricultural", "plastic_mulch_layer", "Plastic Mulch Layer", "percent", 15, "planning"],
  ["agricultural", "self_propelled_sprayer", "Self-Propelled Sprayer", "hours", 8000, "existing"],
  ["agricultural", "mounted_boom_sprayer", "Mounted Boom Sprayer", "percent", 15, "planning"],
  ["agricultural", "trailed_boom_sprayer", "Trailed Boom Sprayer", "percent", 15, "planning"],
  ["agricultural", "mounted_orchard_sprayer", "Mounted Orchard Sprayer", "percent", 15, "planning"],
  ["agricultural", "trailed_orchard_sprayer", "Trailed Orchard Sprayer", "percent", 15, "planning"],
  ["agricultural", "mounted_fertiliser_spreader", "Mounted Fertiliser Spreader", "percent", 15, "planning"],
  ["agricultural", "trailed_fertiliser_spreader", "Trailed Fertiliser Spreader", "percent", 15, "planning"],
  ["agricultural", "lime_bulk_spreader", "Lime & Bulk Spreader", "percent", 15, "planning"],
  ["agricultural", "manure_spreader", "Manure & Compost Spreader", "percent", 15, "planning"],
  ["agricultural", "crop_application_drone", "Crop Spraying Drone", "hours", 2000, "planning"],
  ["agricultural", "plough", "Plough", "percent", 20, "planning"],
  ["agricultural", "chisel_plough", "Chisel Plough", "percent", 20, "planning"],
  ["agricultural", "ripper_subsoiler", "Ripper / Subsoiler", "percent", 20, "planning"],
  ["agricultural", "field_cultivator", "Field Cultivator", "percent", 20, "planning"],
  ["agricultural", "inter_row_cultivator", "Inter-Row Cultivator", "percent", 20, "planning"],
  ["agricultural", "disc_harrow", "Disc Harrow", "percent", 20, "planning"],
  ["agricultural", "tine_harrow", "Tine Harrow", "percent", 20, "planning"],
  ["agricultural", "power_harrow", "Power Harrow", "percent", 20, "planning"],
  ["agricultural", "rotary_tiller", "Rotary Tiller", "percent", 20, "planning"],
  ["agricultural", "land_roller", "Land Roller", "percent", 20, "planning"],
  ["agricultural", "pasture_aerator", "Pasture Aerator", "percent", 20, "planning"],
  ["agricultural", "bed_former_ridger", "Bed Former / Ridger", "percent", 20, "planning"],
  ["agricultural", "rock_picker", "Rock Picker", "percent", 20, "planning"],
  ["agricultural", "slasher", "Slasher", "percent", 15, "planning"],
  ["agricultural", "flail_mulcher", "Flail Mulcher", "percent", 15, "planning"],
  ["agricultural", "pto_wood_chipper", "Tractor PTO Wood Chipper", "percent", 15, "planning"],
  ["agricultural", "engine_wood_chipper", "Engine-Powered Wood Chipper", "hours", 6000, "planning"],
  ["agricultural", "mounted_orchard_sweeper", "Mounted Orchard Sweeper", "percent", 15, "planning"],
  ["agricultural", "trailed_orchard_sweeper", "Trailed Orchard Sweeper", "percent", 15, "planning"],
  ["agricultural", "mounted_orchard_blower", "Mounted Orchard Blower", "percent", 15, "planning"],
  ["agricultural", "trailed_orchard_blower", "Trailed Orchard Blower", "percent", 15, "planning"],
  ["agricultural", "orchard_weeder", "Orchard / Vineyard Weeder", "percent", 15, "planning"],
  ["agricultural", "orchard_pruner", "Orchard / Vineyard Pruner", "percent", 15, "planning"],
  ["agricultural", "orchard_platform", "Orchard Picking Platform", "percent", 15, "planning"],
  ["agricultural", "feed_mixer_wagon", "Feed Mixer Wagon", "percent", 15, "planning"],
  ["agricultural", "stationary_feed_mixer", "Stationary Feed Mixer", "percent", 15, "planning"],
  ["agricultural", "feedout_wagon", "Feedout Wagon", "percent", 15, "planning"],
  ["agricultural", "self_loading_forage_wagon", "Self-Loading Forage Wagon", "percent", 15, "planning"],
  ["agricultural", "hammer_mill", "Hammer Mill", "percent", 15, "planning"],
  ["agricultural", "feed_roller_mill", "Feed Roller Mill", "percent", 15, "planning"],
  ["agricultural", "feed_pellet_mill", "Feed Pellet Mill", "percent", 15, "planning"],
  ["agricultural", "farm_flatbed_trailer", "Farm Flatbed / Dropside Trailer", "percent", 20, "planning"],
  ["agricultural", "farm_tipping_trailer", "Farm Tipping Trailer", "percent", 20, "planning"],
  ["agricultural", "silage_trailer", "Silage Trailer", "percent", 20, "planning"],
  ["agricultural", "grain_cart", "Grain Cart / Chaser Bin", "percent", 20, "planning"],
  ["agricultural", "seed_fertiliser_tender", "Seed & Fertiliser Tender", "percent", 20, "planning"],
  ["agricultural", "cane_trailer", "Cane Trailer", "percent", 20, "planning"],
  ["agricultural", "grain_bagger", "Grain Bagger", "percent", 15, "planning"],
  ["agricultural", "grain_bag_extractor", "Grain Bag Extractor", "percent", 15, "planning"],
  ["agricultural", "grain_auger", "Grain Auger", "percent", 15, "planning"],
  ["agricultural", "grain_conveyor", "Grain Conveyor", "percent", 15, "planning"],
  ["agricultural", "grain_cleaner", "Grain Cleaner", "percent", 15, "planning"],
  ["agricultural", "grain_dryer", "Grain Dryer", "percent", 15, "planning"],
  ["agricultural", "crop_thresher", "Thresher / Maize Sheller", "percent", 15, "planning"],
  ["agricultural", "groundnut_sheller", "Groundnut Sheller", "percent", 15, "planning"],
  ["agricultural", "crop_grader", "Crop Grader", "percent", 15, "planning"],
  ["agricultural", "crop_washer", "Crop Washer", "percent", 15, "planning"],
  ["agricultural", "cattle_crush", "Cattle Crush", "percent", 20, "planning"],
  ["agricultural", "sheep_goat_handling_crate", "Sheep / Goat Handling Crate", "percent", 20, "planning"],
  ["agricultural", "livestock_weighing_scale", "Livestock Scale", "percent", 10, "planning"],
  ["agricultural", "livestock_loading_ramp", "Livestock Loading Ramp", "percent", 20, "planning"],
  ["agricultural", "livestock_spray_race", "Livestock Spray Race", "percent", 20, "planning"],
  ["agricultural", "livestock_self_feeder", "Livestock Self-Feeder", "percent", 20, "planning"],
  ["agricultural", "sheep_shearing_machine", "Sheep Shearing Machine", "percent", 10, "planning"],
  ["agricultural", "portable_milking_machine", "Portable Milking Machine", "percent", 15, "planning"],
  ["agricultural", "milk_cooling_tank", "Milk Cooling Tank", "percent", 15, "planning"],
  ["agricultural", "automatic_calf_feeder", "Automatic Calf Feeder", "percent", 10, "planning"],
  ["agricultural", "egg_incubator", "Egg Incubator", "percent", 10, "planning"],
  ["agricultural", "centre_pivot_irrigator", "Centre Pivot Irrigator", "percent", 20, "planning"],
  ["agricultural", "linear_irrigator", "Linear Irrigator", "percent", 20, "planning"],
  ["agricultural", "hose_reel_irrigator", "Hose-Reel Irrigator", "percent", 20, "planning"],
  ["agricultural", "cable_drawn_irrigator", "Cable-Drawn Irrigator", "percent", 20, "planning"],
  ["agricultural", "dam_scoop_scraper", "Dam Scoop / Scraper", "percent", 20, "planning"],
  ["agricultural", "land_leveller", "Land Leveller", "percent", 20, "planning"],
  ["agricultural", "mounted_tractor_grader", "Mounted Tractor Grader", "percent", 20, "planning"],
  ["agricultural", "trailed_tractor_grader", "Trailed Tractor Grader", "percent", 20, "planning"],
  ["agricultural", "tractor_front_loader", "Tractor Front Loader", "percent", 20, "planning"],
  ["agricultural", "tractor_post_hole_digger", "Tractor Post-Hole Digger", "percent", 20, "planning"],
  ["agricultural", "skid_firefighting_unit", "Bakkie Firefighting Unit", "percent", 20, "planning"],
  ["agricultural", "farm_firefighting_trailer", "Farm Firefighting Trailer", "percent", 20, "planning"],
  ["construction", "mini_excavator", "Mini Excavator", "hours", 8000, "planning"],
  ["construction", "tracked_excavator", "Tracked Excavator", "hours", 12000, "existing"],
  ["construction", "wheeled_excavator", "Wheeled Excavator", "hours", 12000, "existing"],
  ["construction", "long_reach_excavator", "Long Reach Excavator", "hours", 12000, "existing"],
  ["construction", "high_reach_demolition_excavator", "High Reach Demolition Excavator", "hours", 12000, "existing"],
  ["construction", "backhoe_loader", "TLB / Backhoe Loader", "hours", 12000, "existing"],
  ["construction", "bulldozer", "Bulldozer", "hours", 12000, "existing"],
  ["construction", "motor_grader", "Motor Grader", "hours", 12000, "existing"],
  ["construction", "wheel_loader", "Front End Loader", "hours", 10000, "existing"],
  ["construction", "compact_wheel_loader", "Compact Front End Loader", "hours", 10000, "existing"],
  ["construction", "skid_steer_loader", "Skid Steer Loader", "hours", 8000, "planning"],
  ["construction", "compact_track_loader", "Compact Track Loader", "hours", 8000, "planning"],
  ["construction", "stand_on_mini_loader", "Stand-On Mini Loader", "hours", 8000, "planning"],
  ["construction", "crawler_loader", "Crawler Front End Loader", "hours", 10000, "existing"],
  ["construction", "articulated_dump_truck", "Articulated Dump Truck", "hours", 15000, "planning"],
  ["construction", "rigid_dump_truck", "Rigid Dump Truck", "hours", 20000, "planning"],
  ["construction", "site_dumper", "Site Dumper", "hours", 8000, "planning"],
  ["construction", "tracked_site_dumper", "Tracked Site Dumper", "hours", 8000, "planning"],
  ["construction", "tracked_dump_carrier", "Tracked Dump Carrier", "hours", 8000, "planning"],
  ["construction", "off_road_water_tanker", "Off-Road Water Tanker", "hours", 15000, "planning"],
  ["construction", "compaction_rammer", "Compaction Rammer", "percent", 10, "planning"],
  ["construction", "forward_plate_compactor", "Forward Plate Compactor", "percent", 10, "planning"],
  ["construction", "reversible_plate_compactor", "Reversible Plate Compactor", "percent", 10, "planning"],
  ["construction", "walk_behind_roller", "Walk-Behind Roller", "percent", 10, "planning"],
  ["construction", "trench_roller", "Trench Roller", "percent", 10, "planning"],
  ["construction", "tandem_road_roller", "Tandem Road Roller", "hours", 10000, "planning"],
  ["construction", "smooth_drum_soil_roller", "Smooth Drum Soil Roller", "hours", 10000, "planning"],
  ["construction", "padfoot_soil_roller", "Padfoot Soil Roller", "hours", 10000, "planning"],
  ["construction", "pneumatic_tyre_roller", "Pneumatic Tyre Roller", "hours", 10000, "planning"],
  ["construction", "towed_impact_roller", "Towed Impact Roller", "percent", 15, "planning"],
  ["construction", "towed_grid_roller", "Towed Grid Roller", "percent", 15, "planning"],
  ["construction", "combination_road_roller", "Combination Road Roller", "hours", 10000, "planning"],
  ["construction", "tracked_asphalt_paver", "Tracked Asphalt Paver", "hours", 10000, "planning"],
  ["construction", "wheeled_asphalt_paver", "Wheeled Asphalt Paver", "hours", 10000, "planning"],
  ["construction", "road_milling_machine", "Road Milling Machine", "hours", 10000, "planning"],
  ["construction", "road_recycler_stabiliser", "Road Recycler / Stabiliser", "hours", 10000, "planning"],
  ["construction", "tractor_soil_stabiliser", "Tractor Soil Stabiliser", "percent", 15, "planning"],
  ["construction", "asphalt_material_feeder", "Asphalt Material Feeder", "hours", 10000, "planning"],
  ["construction", "concrete_kerb_paver", "Concrete Kerb Paver", "hours", 10000, "planning"],
  ["construction", "concrete_road_paver", "Concrete Road Paver", "hours", 10000, "planning"],
  ["construction", "portable_bitumen_sprayer", "Portable Bitumen Sprayer", "percent", 10, "planning"],
  ["construction", "trailed_bitumen_sprayer", "Trailed Bitumen Sprayer", "hours", 10000, "planning"],
  ["construction", "self_propelled_chip_spreader", "Self-Propelled Chip Spreader", "hours", 10000, "planning"],
  ["construction", "walk_behind_line_marker", "Walk-Behind Line Marker", "percent", 10, "planning"],
  ["construction", "ride_on_line_marker", "Ride-On Line Marker", "hours", 10000, "planning"],
  ["construction", "portable_concrete_mixer", "Portable Concrete Mixer", "percent", 10, "planning"],
  ["construction", "towable_concrete_mixer", "Towable Concrete Mixer", "percent", 10, "planning"],
  ["construction", "skip_fed_concrete_mixer", "Skip-Fed Concrete Mixer", "percent", 10, "planning"],
  ["construction", "self_loading_concrete_mixer", "Self-Loading Concrete Mixer", "hours", 10000, "planning"],
  ["construction", "tractor_concrete_mixer", "Tractor Concrete Mixer", "percent", 15, "planning"],
  ["construction", "stationary_concrete_pump", "Stationary Concrete Pump", "hours", 10000, "planning"],
  ["construction", "trailer_concrete_pump", "Trailer Concrete Pump", "hours", 10000, "planning"],
  ["construction", "truck_concrete_boom_pump", "Truck Concrete Boom Pump", "hours", 10000, "planning"],
  ["construction", "concrete_placing_boom", "Concrete Placing Boom", "percent", 15, "planning"],
  ["construction", "shotcrete_machine", "Shotcrete Machine", "hours", 10000, "planning"],
  ["construction", "grout_pump", "Grout Pump", "percent", 10, "planning"],
  ["construction", "concrete_mixer_placer", "Concrete Mixer & Placer", "hours", 10000, "planning"],
  ["construction", "concrete_poker_vibrator", "Concrete Poker Vibrator", "percent", 10, "planning"],
  ["construction", "powered_concrete_screed", "Powered Concrete Screed", "percent", 10, "planning"],
  ["construction", "laser_concrete_screed", "Laser Concrete Screed", "hours", 6000, "planning"],
  ["construction", "walk_behind_power_float", "Walk-Behind Power Float", "percent", 10, "planning"],
  ["construction", "ride_on_power_float", "Ride-On Power Float", "hours", 6000, "planning"],
  ["construction", "walk_behind_trencher", "Walk-Behind Trencher", "hours", 4000, "planning"],
  ["construction", "ride_on_trencher", "Ride-On Trencher", "hours", 12000, "existing"],
  ["construction", "pipeline_trencher", "Pipeline Trencher", "hours", 12000, "existing"],
  ["construction", "directional_drilling_rig", "Directional Drilling Rig", "hours", 12000, "existing"],
  ["construction", "piling_drill_rig", "Piling Drill Rig", "hours", 12000, "existing"],
  ["construction", "pile_driving_rig", "Pile Driving Rig", "hours", 12000, "existing"],
  ["construction", "anchor_drilling_rig", "Anchor Drilling Rig", "hours", 12000, "existing"],
  ["construction", "solar_pile_driver", "Solar Pile Driver", "hours", 12000, "existing"],
  ["construction", "truck_vacuum_excavator", "Truck Vacuum Excavator", "hours", 12000, "existing"],
  ["construction", "vacuum_excavation_unit", "Vacuum Excavation Unit", "hours", 12000, "existing"],
  ["construction", "all_terrain_crane", "All Terrain Crane", "hours", 10000, "planning"],
  ["construction", "rough_terrain_crane", "Rough Terrain Crane", "hours", 10000, "planning"],
  ["construction", "truck_crane", "Truck Crane", "hours", 10000, "planning"],
  ["construction", "lattice_crawler_crane", "Lattice Boom Crawler Crane", "hours", 10000, "planning"],
  ["construction", "telescopic_crawler_crane", "Telescopic Crawler Crane", "hours", 10000, "planning"],
  ["construction", "spider_crane", "Spider Crane", "hours", 10000, "planning"],
  ["construction", "city_crane", "City Crane", "hours", 10000, "planning"],
  ["construction", "carry_deck_crane", "Carry Deck Crane", "hours", 10000, "planning"],
  ["construction", "tower_crane", "Tower Crane", "percent", 25, "planning"],
  ["construction", "luffing_tower_crane", "Luffing Tower Crane", "percent", 25, "planning"],
  ["construction", "self_erecting_tower_crane", "Self Erecting Tower Crane", "percent", 25, "planning"],
  ["construction", "articulated_boom_lift", "Articulated Boom Lift", "hours", 8000, "planning"],
  ["construction", "telescopic_boom_lift", "Telescopic Boom Lift", "hours", 8000, "planning"],
  ["construction", "slab_scissor_lift", "Slab Scissor Lift", "hours", 8000, "planning"],
  ["construction", "rough_terrain_scissor_lift", "Rough Terrain Scissor Lift", "hours", 8000, "planning"],
  ["construction", "trailer_boom_lift", "Trailer Boom Lift", "hours", 8000, "planning"],
  ["construction", "spider_boom_lift", "Spider Boom Lift", "hours", 8000, "planning"],
  ["construction", "mast_boom_lift", "Mast Boom Lift", "hours", 8000, "planning"],
  ["construction", "push_around_personnel_lift", "Push-Around Personnel Lift", "percent", 15, "planning"],
  ["construction", "construction_hoist", "Construction Hoist", "percent", 15, "planning"],
  ["construction", "ladder_material_hoist", "Ladder Material Hoist", "percent", 15, "planning"],
  ["construction", "mast_climbing_platform", "Mast Climbing Work Platform", "percent", 15, "planning"],
  ["construction", "suspended_work_platform", "Suspended Work Platform", "percent", 15, "planning"],
  ["construction", "mobile_scaffold_tower", "Mobile Scaffold Tower", "percent", 15, "planning"],
  ["construction", "self_propelled_personnel_lift", "Self-Propelled Personnel Lift", "hours", 8000, "planning"],
  ["construction", "fixed_telehandler", "Fixed Telehandler", "hours", 10000, "existing"],
  ["construction", "rotating_telehandler", "Rotating Telehandler", "hours", 10000, "existing"],
  ["construction", "excavator_bucket", "Excavator Bucket", "percent", 15, "planning"],
  ["construction", "loader_bucket", "Loader Bucket", "percent", 15, "planning"],
  ["construction", "four_in_one_bucket", "4-in-1 Bucket", "percent", 15, "planning"],
  ["construction", "grapple_bucket", "Grapple Bucket", "percent", 15, "planning"],
  ["construction", "hydraulic_breaker_attachment", "Hydraulic Breaker Attachment", "percent", 15, "planning"],
  ["construction", "earth_auger_attachment", "Earth Auger Attachment", "percent", 15, "planning"],
  ["construction", "excavator_grab", "Excavator Grab", "percent", 15, "planning"],
  ["construction", "concrete_pulveriser", "Concrete Pulveriser", "percent", 15, "planning"],
  ["construction", "demolition_cutter", "Demolition Cutter", "percent", 15, "planning"],
  ["construction", "crusher_bucket", "Crusher Bucket", "percent", 15, "planning"],
  ["construction", "screening_bucket", "Screening Bucket", "percent", 15, "planning"],
  ["construction", "drum_cutter_attachment", "Drum Cutter Attachment", "percent", 15, "planning"],
  ["construction", "compactor_attachment", "Compactor Attachment", "percent", 15, "planning"],
  ["construction", "excavator_ripper", "Excavator Ripper", "percent", 15, "planning"],
  ["construction", "sweeper_attachment", "Sweeper Attachment", "percent", 15, "planning"],
  ["construction", "loader_pallet_forks", "Loader Pallet Forks", "percent", 15, "planning"],
  ["construction", "trencher_attachment", "Trencher Attachment", "percent", 15, "planning"],
  ["construction", "road_planer_attachment", "Road Planer Attachment", "percent", 15, "planning"],
  ["construction", "mobile_jaw_crusher", "Mobile Jaw Crusher", "hours", 10000, "planning"],
  ["construction", "mobile_cone_crusher", "Mobile Cone Crusher", "hours", 10000, "planning"],
  ["construction", "mobile_impact_crusher", "Mobile Impact Crusher", "hours", 10000, "planning"],
  ["construction", "mobile_screen", "Mobile Screening Plant", "hours", 10000, "planning"],
  ["construction", "mobile_trommel", "Mobile Trommel Screen", "hours", 10000, "planning"],
  ["construction", "mobile_stacking_conveyor", "Mobile Stacking Conveyor", "hours", 10000, "planning"],
  ["construction", "floor_saw", "Floor Saw", "percent", 10, "planning"],
  ["construction", "early_entry_saw", "Early Entry Concrete Saw", "percent", 10, "planning"],
  ["construction", "handheld_concrete_saw", "Handheld Concrete Saw", "percent", 10, "planning"],
  ["construction", "masonry_saw", "Masonry Saw", "percent", 10, "planning"],
  ["construction", "tile_saw", "Tile Saw", "percent", 10, "planning"],
  ["construction", "wall_saw", "Wall Saw", "percent", 10, "planning"],
  ["construction", "wire_saw", "Wire Saw", "percent", 10, "planning"],
  ["construction", "core_drill_rig", "Concrete Core Drill Rig", "percent", 10, "planning"],
  ["construction", "handheld_core_drill", "Handheld Core Drill", "percent", 10, "planning"],
  ["construction", "demolition_robot", "Demolition Robot", "hours", 6000, "planning"],
  ["construction", "electric_demolition_hammer", "Electric Demolition Hammer", "percent", 10, "planning"],
  ["construction", "pneumatic_breaker", "Pneumatic Breaker", "percent", 10, "planning"],
  ["construction", "hydraulic_handheld_breaker", "Hydraulic Handheld Breaker", "percent", 10, "planning"],
  ["construction", "petrol_breaker", "Petrol Breaker", "percent", 10, "planning"],
  ["construction", "floor_grinder", "Floor Grinder", "percent", 10, "planning"],
  ["construction", "floor_scarifier", "Floor Scarifier", "percent", 10, "planning"],
  ["construction", "floor_shot_blaster", "Floor Shot Blaster", "percent", 10, "planning"],
  ["construction", "walk_behind_floor_scraper", "Walk-Behind Floor Scraper", "percent", 10, "planning"],
  ["construction", "ride_on_floor_scraper", "Ride-On Floor Scraper", "hours", 6000, "planning"],
  ["construction", "rebar_cutter", "Rebar Cutter", "percent", 15, "planning"],
  ["construction", "rebar_bender", "Rebar Bender", "percent", 15, "planning"],
  ["construction", "rebar_cutter_bender", "Rebar Cutter & Bender", "percent", 15, "planning"],
  ["construction", "manual_total_station", "Manual Total Station", "percent", 8, "planning"],
  ["construction", "robotic_total_station", "Robotic Total Station", "percent", 8, "planning"],
  ["construction", "survey_gnss_rover", "Survey GPS / GNSS Rover", "percent", 8, "planning"],
  ["construction", "dumpy_level", "Dumpy / Automatic Level", "percent", 8, "planning"],
  ["construction", "digital_survey_level", "Digital Survey Level", "percent", 8, "planning"],
  ["construction", "construction_laser_level", "Construction Laser Level", "percent", 8, "planning"],
  ["construction", "pipe_laser", "Pipe Laser", "percent", 8, "planning"],
  ["construction", "theodolite", "Theodolite", "percent", 8, "planning"],
  ["construction", "survey_laser_scanner", "Survey Laser Scanner", "percent", 8, "planning"],
  ["industrial", "articulated_forklift", "Articulated Forklift", "hours", 10000, "toyota"],
  ["industrial", "container_reach_stacker", "Container Reach Stacker", "hours", 15000, "planning"],
  ["industrial", "diesel_counterbalance_forklift", "Diesel Forklift", "hours", 10000, "toyota"],
  ["industrial", "gas_counterbalance_forklift", "Gas / Petrol Forklift", "hours", 10000, "toyota"],
  ["industrial", "electric_counterbalance_forklift", "Electric Forklift", "hours", 10000, "toyota"],
  ["industrial", "multidirectional_forklift", "Multidirectional Forklift", "hours", 10000, "toyota"],
  ["industrial", "rough_terrain_forklift", "Rough Terrain Forklift", "hours", 10000, "toyota"],
  ["industrial", "side_loader_forklift", "Side Loader Forklift", "hours", 10000, "toyota"],
  ["industrial", "drum_lifter_tipper", "Drum Lifter & Tipper", "percent", 15, "planning"],
  ["industrial", "fixed_lift_table", "Fixed Lift Table", "percent", 15, "planning"],
  ["industrial", "manual_pallet_jack", "Manual Pallet Jack", "percent", 15, "planning"],
  ["industrial", "manual_pallet_stacker", "Manual Pallet Stacker", "percent", 15, "planning"],
  ["industrial", "manual_mobile_lift_table", "Manual Mobile Lift Table", "percent", 15, "planning"],
  ["industrial", "powered_mobile_lift_table", "Powered Mobile Lift Table", "percent", 15, "planning"],
  ["industrial", "order_picker", "Order Picker", "hours", 10000, "planning"],
  ["industrial", "pallet_inverter", "Pallet Inverter", "percent", 15, "planning"],
  ["industrial", "powered_pallet_stacker", "Powered Pallet Stacker", "hours", 10000, "planning"],
  ["industrial", "powered_pallet_truck", "Powered Pallet Truck", "hours", 10000, "planning"],
  ["industrial", "reach_truck", "Reach Truck", "hours", 10000, "planning"],
  ["industrial", "turret_truck", "Turret Truck", "hours", 10000, "planning"],
  ["industrial", "warehouse_tow_tractor", "Warehouse Tow Tractor", "hours", 10000, "planning"],
  ["industrial", "air_chain_hoist", "Air Chain Hoist", "percent", 20, "planning"],
  ["industrial", "electric_chain_hoist", "Electric Chain Hoist", "percent", 20, "planning"],
  ["industrial", "engine_crane", "Engine Crane", "percent", 15, "planning"],
  ["industrial", "industrial_gantry_crane", "Industrial Gantry Crane", "percent", 20, "planning"],
  ["industrial", "jib_crane", "Jib Crane", "percent", 20, "planning"],
  ["industrial", "lever_hoist", "Lever Hoist", "percent", 15, "planning"],
  ["industrial", "manual_chain_block", "Manual Chain Block", "percent", 15, "planning"],
  ["industrial", "overhead_travelling_crane", "Overhead Crane", "percent", 20, "planning"],
  ["industrial", "wire_rope_hoist", "Wire Rope Hoist", "percent", 20, "planning"],
  ["industrial", "workshop_gantry", "Workshop Gantry", "percent", 15, "planning"],
  ["industrial", "dock_leveller", "Dock Leveller", "hours", 40000, "planning"],
  ["industrial", "gravity_roller_conveyor", "Gravity Roller Conveyor", "percent", 15, "planning"],
  ["industrial", "industrial_belt_conveyor", "Industrial Belt Conveyor", "hours", 40000, "planning"],
  ["industrial", "industrial_bucket_elevator", "Industrial Bucket Elevator", "hours", 40000, "planning"],
  ["industrial", "industrial_screw_conveyor", "Industrial Screw Conveyor", "hours", 40000, "planning"],
  ["industrial", "powered_roller_conveyor", "Powered Roller Conveyor", "hours", 40000, "planning"],
  ["industrial", "band_sealer", "Band Sealer", "percent", 15, "planning"],
  ["industrial", "bottle_capping_machine", "Bottle Capping Machine", "hours", 20000, "planning"],
  ["industrial", "carton_sealer", "Carton Sealer", "percent", 15, "planning"],
  ["industrial", "cartoning_machine", "Cartoning Machine", "percent", 15, "planning"],
  ["industrial", "case_packer", "Case Packer", "percent", 15, "planning"],
  ["industrial", "chamber_vacuum_packer", "Chamber Vacuum Packer", "percent", 15, "planning"],
  ["industrial", "cup_filling_sealing_machine", "Cup Filling & Sealing Machine", "percent", 15, "planning"],
  ["industrial", "external_vacuum_sealer", "External Vacuum Sealer", "percent", 15, "planning"],
  ["industrial", "flow_wrapper", "Flow Wrapper", "percent", 15, "planning"],
  ["industrial", "labelling_machine", "Labelling Machine", "percent", 15, "planning"],
  ["industrial", "liquid_filling_machine", "Liquid Filling Machine", "hours", 20000, "planning"],
  ["industrial", "orbital_wrapper", "Orbital Wrapper", "percent", 15, "planning"],
  ["industrial", "pouch_filling_machine", "Pouch Filling Machine", "percent", 15, "planning"],
  ["industrial", "robot_pallet_wrapper", "Robot Pallet Wrapper", "percent", 15, "planning"],
  ["industrial", "rotary_arm_pallet_wrapper", "Rotary Arm Pallet Wrapper", "percent", 15, "planning"],
  ["industrial", "shrink_sleeve_labeller", "Shrink Sleeve Labeller", "percent", 15, "planning"],
  ["industrial", "shrink_wrapper", "Shrink Wrapper", "percent", 15, "planning"],
  ["industrial", "strapping_machine", "Strapping Machine", "percent", 15, "planning"],
  ["industrial", "tube_filling_sealing_machine", "Tube Filling & Sealing Machine", "percent", 15, "planning"],
  ["industrial", "turntable_pallet_wrapper", "Turntable Pallet Wrapper", "percent", 15, "planning"],
  ["industrial", "vertical_bagging_machine", "Vertical Bagging Machine", "percent", 15, "planning"],
  ["industrial", "bag_waste_compactor", "Bag Waste Compactor", "hours", 20000, "planning"],
  ["industrial", "drum_crusher", "Drum Crusher", "hours", 20000, "planning"],
  ["industrial", "horizontal_recycling_baler", "Horizontal Recycling Baler", "hours", 20000, "planning"],
  ["industrial", "industrial_waste_shredder", "Industrial Waste Shredder", "hours", 20000, "planning"],
  ["industrial", "plastic_granulator", "Plastic Granulator", "hours", 20000, "planning"],
  ["industrial", "plastic_pulveriser", "Plastic Pulveriser", "hours", 20000, "planning"],
  ["industrial", "scrap_metal_baler", "Scrap Metal Baler", "hours", 20000, "planning"],
  ["industrial", "self_contained_waste_compactor", "Self-Contained Waste Compactor", "hours", 20000, "planning"],
  ["industrial", "static_waste_compactor", "Static Waste Compactor", "hours", 20000, "planning"],
  ["industrial", "vertical_recycling_baler", "Vertical Recycling Baler", "hours", 20000, "planning"],
  ["industrial", "wheelie_bin_compactor", "Wheelie Bin Compactor", "hours", 20000, "planning"],
  ["industrial", "battery_energy_storage_unit", "Battery Energy Storage Unit", "percent", 10, "planning"],
  ["industrial", "container_generator", "Container Generator", "hours", 15000, "existing"],
  ["industrial", "diesel_generator_set", "Diesel Generator Set", "hours", 15000, "existing"],
  ["industrial", "gas_generator_set", "Gas Generator Set", "hours", 15000, "existing"],
  ["industrial", "inverter_generator", "Inverter Generator", "hours", 3000, "planning"],
  ["industrial", "portable_diesel_generator", "Portable Diesel Generator", "hours", 8000, "planning"],
  ["industrial", "portable_petrol_generator", "Portable Petrol Generator", "hours", 3000, "planning"],
  ["industrial", "trailer_generator", "Trailer Generator", "hours", 15000, "existing"],
  ["industrial", "air_receiver", "Air Receiver Tank", "percent", 20, "planning"],
  ["industrial", "centrifugal_air_compressor", "Centrifugal Air Compressor", "hours", 20000, "planning"],
  ["industrial", "desiccant_air_dryer", "Desiccant Air Dryer", "percent", 15, "planning"],
  ["industrial", "industrial_air_blower", "Industrial Air Blower", "hours", 20000, "planning"],
  ["industrial", "industrial_vacuum_pump", "Industrial Vacuum Pump", "hours", 20000, "planning"],
  ["industrial", "liquid_ring_vacuum_pump", "Liquid Ring Vacuum Pump", "hours", 20000, "planning"],
  ["industrial", "skid_jobsite_air_compressor", "Skid-Mounted Site Compressor", "hours", 12000, "existing"],
  ["industrial", "towable_jobsite_air_compressor", "Towable Site Compressor", "hours", 12000, "existing"],
  ["industrial", "nitrogen_generator", "Nitrogen Generator", "percent", 15, "planning"],
  ["industrial", "oil_free_air_compressor", "Oil-free Air Compressor", "hours", 20000, "planning"],
  ["industrial", "oxygen_generator", "Oxygen Generator", "percent", 15, "planning"],
  ["industrial", "piston_air_compressor", "Piston Air Compressor", "hours", 12000, "existing"],
  ["industrial", "refrigerated_air_dryer", "Refrigerated Air Dryer", "percent", 15, "planning"],
  ["industrial", "screw_air_compressor", "Screw Air Compressor", "hours", 20000, "planning"],
  ["industrial", "borehole_pump", "Borehole Pump", "hours", 20000, "planning"],
  ["industrial", "chemical_process_pump", "Chemical Process Pump", "hours", 20000, "planning"],
  ["industrial", "diaphragm_transfer_pump", "Diaphragm Transfer Pump", "hours", 20000, "planning"],
  ["industrial", "dosing_pump", "Dosing Pump", "hours", 20000, "planning"],
  ["industrial", "drum_transfer_pump", "Drum Transfer Pump", "hours", 20000, "planning"],
  ["industrial", "fixed_fire_pump_set", "Fire Pump Set", "hours", 20000, "planning"],
  ["industrial", "hose_pump", "Hose Pump", "hours", 20000, "planning"],
  ["industrial", "hydraulic_power_pack", "Hydraulic Power Pack", "hours", 20000, "planning"],
  ["industrial", "hygienic_process_pump", "Hygienic Process Pump", "hours", 20000, "planning"],
  ["industrial", "multistage_water_pump", "Multistage Water Pump", "hours", 20000, "planning"],
  ["industrial", "portable_trash_pump", "Portable Trash Pump", "hours", 8000, "planning"],
  ["industrial", "portable_water_pump", "Portable Water Pump", "hours", 8000, "planning"],
  ["industrial", "progressive_cavity_pump", "Progressive Cavity Pump", "hours", 20000, "planning"],
  ["industrial", "sewage_pump", "Sewage Pump", "hours", 20000, "planning"],
  ["industrial", "slurry_pump", "Slurry Pump", "hours", 20000, "planning"],
  ["industrial", "submersible_drainage_pump", "Submersible Drainage Pump", "hours", 20000, "planning"],
  ["industrial", "surface_dewatering_pump", "Surface Dewatering Pump", "hours", 8000, "planning"],
  ["industrial", "water_booster_set", "Water Booster Set", "hours", 20000, "planning"],
  ["industrial", "centrifugal_water_pump", "Water Transfer Pump", "hours", 20000, "planning"],
  ["industrial", "wellpoint_pump", "Wellpoint Pump", "hours", 8000, "planning"],
  ["industrial", "battery_solar_lighting_tower", "Battery & Solar Lighting Tower", "percent", 10, "planning"],
  ["industrial", "diesel_lighting_tower", "Diesel Lighting Tower", "hours", 8000, "planning"],
  ["industrial", "plug_in_lighting_tower", "Plug-in Lighting Tower", "percent", 10, "planning"],
  ["industrial", "carpet_extractor", "Carpet Extractor", "percent", 8, "planning"],
  ["industrial", "cold_water_pressure_washer", "Cold-water Pressure Washer", "percent", 8, "planning"],
  ["industrial", "commercial_vacuum_cleaner", "Commercial Vacuum Cleaner", "percent", 8, "planning"],
  ["industrial", "dry_ice_blaster", "Dry Ice Blaster", "percent", 8, "planning"],
  ["industrial", "floor_polisher", "Floor Polisher", "percent", 8, "planning"],
  ["industrial", "hot_water_pressure_washer", "Hot-water Pressure Washer", "percent", 8, "planning"],
  ["industrial", "industrial_vacuum_cleaner", "Industrial Vacuum Cleaner", "percent", 8, "planning"],
  ["industrial", "ride_on_scrubber_dryer", "Ride-on Scrubber Dryer", "hours", 6000, "planning"],
  ["industrial", "ride_on_sweeper", "Ride-on Sweeper", "hours", 6000, "planning"],
  ["industrial", "steam_cleaner", "Steam Cleaner", "percent", 8, "planning"],
  ["industrial", "sweeper_scrubber", "Sweeper Scrubber", "hours", 6000, "planning"],
  ["industrial", "walk_behind_scrubber_dryer", "Walk-behind Scrubber Dryer", "hours", 4000, "planning"],
  ["industrial", "walk_behind_sweeper", "Walk-behind Sweeper", "hours", 4000, "planning"],
  ["industrial", "air_cooled_chiller", "Air-cooled Chiller", "percent", 20, "planning"],
  ["industrial", "cooling_tower", "Cooling Tower", "percent", 20, "ashrae_context"],
  ["industrial", "hot_water_boiler", "Hot-water Boiler", "percent", 20, "ashrae_context"],
  ["industrial", "industrial_dehumidifier", "Industrial Dehumidifier", "percent", 12, "planning"],
  ["industrial", "steam_boiler", "Steam Boiler", "percent", 20, "planning"],
  ["industrial", "thermal_oil_heater", "Thermal Oil Heater", "percent", 20, "planning"],
  ["industrial", "water_cooled_chiller", "Water-cooled Chiller", "percent", 25, "ashrae_context"],
  ["industrial", "bench_grinder", "Bench Grinder", "percent", 15, "planning"],
  ["industrial", "cnc_lathe", "CNC Lathe", "hours", 40000, "planning"],
  ["industrial", "cnc_machining_centre", "CNC Machining Centre", "hours", 40000, "planning"],
  ["industrial", "cnc_plasma_table", "CNC Plasma Cutter", "hours", 30000, "planning"],
  ["industrial", "cylindrical_grinder", "Cylindrical Grinder", "hours", 30000, "planning"],
  ["industrial", "drill_press", "Drill Press", "hours", 30000, "planning"],
  ["industrial", "horizontal_boring_mill", "Horizontal Boring Mill", "hours", 40000, "planning"],
  ["industrial", "ironworker", "Ironworker", "hours", 30000, "planning"],
  ["industrial", "magnetic_drill", "Magnetic Base Drill", "hours", 30000, "planning"],
  ["industrial", "metal_bandsaw", "Metal Bandsaw", "hours", 30000, "planning"],
  ["industrial", "metal_cold_saw", "Metal Cold Saw", "hours", 30000, "planning"],
  ["industrial", "manual_metal_lathe", "Metal Lathe", "hours", 30000, "planning"],
  ["industrial", "manual_milling_machine", "Milling Machine", "hours", 30000, "planning"],
  ["industrial", "pipe_bending_machine", "Pipe Bending Machine", "hours", 30000, "planning"],
  ["industrial", "pipe_threading_machine", "Pipe Threading Machine", "hours", 30000, "planning"],
  ["industrial", "plate_roller", "Plate Roller", "hours", 30000, "planning"],
  ["industrial", "power_press", "Power Press", "hours", 30000, "planning"],
  ["industrial", "press_brake", "Press Brake", "hours", 30000, "planning"],
  ["industrial", "radial_drill", "Radial Arm Drill", "hours", 30000, "planning"],
  ["industrial", "section_roller", "Section Roller", "hours", 30000, "planning"],
  ["industrial", "sheet_metal_folder", "Sheet Metal Folder", "hours", 30000, "planning"],
  ["industrial", "sheet_metal_guillotine", "Sheet Metal Guillotine", "hours", 30000, "planning"],
  ["industrial", "metal_sheet_laser_cutter", "Sheet Metal Laser Cutter", "hours", 30000, "planning"],
  ["industrial", "sinker_edm", "Spark Erosion Machine", "hours", 30000, "planning"],
  ["industrial", "surface_grinder", "Surface Grinder", "hours", 30000, "planning"],
  ["industrial", "tube_laser_cutter", "Tube Laser Cutter", "hours", 30000, "planning"],
  ["industrial", "waterjet_cutter", "Waterjet Cutter", "hours", 30000, "planning"],
  ["industrial", "wire_edm", "Wire EDM Machine", "hours", 30000, "planning"],
  ["industrial", "engine_driven_welder", "Engine-Driven Welder", "hours", 8000, "planning"],
  ["industrial", "handheld_laser_welder", "Laser Welder", "percent", 12, "planning"],
  ["industrial", "mig_welder", "MIG Welder", "percent", 12, "planning"],
  ["industrial", "handheld_plasma_cutter", "Plasma Cutter", "percent", 12, "planning"],
  ["industrial", "resistance_spot_welder", "Spot Welder", "percent", 12, "planning"],
  ["industrial", "stick_welder", "Stick Welder", "percent", 12, "planning"],
  ["industrial", "tig_welder", "TIG Welder", "percent", 12, "planning"],
  ["industrial", "beam_panel_saw", "Beam Panel Saw", "hours", 20000, "planning"],
  ["industrial", "wood_belt_disc_sander", "Belt & Disc Sander", "hours", 20000, "planning"],
  ["industrial", "cnc_wood_router", "CNC Wood Router", "hours", 30000, "planning"],
  ["industrial", "combination_woodworking_machine", "Combination Woodworking Machine", "hours", 20000, "planning"],
  ["industrial", "edgebander", "Edgebander", "hours", 20000, "planning"],
  ["industrial", "four_sided_moulder", "Four-Sided Planer & Moulder", "hours", 20000, "planning"],
  ["industrial", "wood_morticer", "Morticer", "hours", 20000, "planning"],
  ["industrial", "wood_boring_machine", "Multi-Boring Machine", "hours", 20000, "planning"],
  ["industrial", "multi_rip_saw", "Multi-Rip Saw", "hours", 20000, "planning"],
  ["industrial", "planer_thicknesser", "Planer Thicknesser", "hours", 20000, "planning"],
  ["industrial", "sawmill_machine", "Sawmill Machine", "hours", 20000, "planning"],
  ["industrial", "sliding_panel_saw", "Sliding Table Panel Saw", "hours", 20000, "planning"],
  ["industrial", "spindle_moulder", "Spindle Moulder", "hours", 20000, "planning"],
  ["industrial", "surface_planer", "Surface Planer", "hours", 20000, "planning"],
  ["industrial", "wood_tenoner", "Tenoner", "hours", 20000, "planning"],
  ["industrial", "wood_thicknesser", "Thicknesser", "hours", 20000, "planning"],
  ["industrial", "vertical_panel_saw", "Vertical Panel Saw", "hours", 20000, "planning"],
  ["industrial", "wide_belt_sander", "Wide Belt Sander", "hours", 20000, "planning"],
  ["industrial", "wood_bandsaw", "Wood Bandsaw", "hours", 20000, "planning"],
  ["industrial", "wood_drum_sander", "Wood Drum Sander", "hours", 20000, "planning"],
  ["industrial", "wood_dust_extractor", "Wood Dust Extractor", "hours", 20000, "planning"],
  ["industrial", "wood_edge_sander", "Wood Edge Sander", "hours", 20000, "planning"],
  ["industrial", "wood_lathe", "Wood Lathe", "hours", 20000, "planning"],
  ["industrial", "wood_mitre_saw", "Wood Mitre Saw", "percent", 15, "planning"],
  ["industrial", "wood_panel_press", "Wood Panel Press", "hours", 20000, "planning"],
  ["industrial", "wood_table_saw", "Wood Table Saw", "hours", 20000, "planning"],
  ["industrial", "vehicle_aircon_service_machine", "Aircon Service Machine", "hours", 15000, "planning"],
  ["industrial", "bench_brake_lathe", "Brake Disc & Drum Lathe", "hours", 15000, "planning"],
  ["industrial", "car_tyre_changer", "Car Tyre Changer", "hours", 15000, "planning"],
  ["industrial", "car_wheel_balancer", "Car Wheel Balancer", "hours", 15000, "planning"],
  ["industrial", "four_post_vehicle_lift", "Four-Post Vehicle Lift", "hours", 15000, "planning"],
  ["industrial", "mobile_column_vehicle_lift", "Mobile Column Vehicle Lift", "hours", 15000, "planning"],
  ["industrial", "on_car_brake_lathe", "On-Car Brake Lathe", "hours", 15000, "planning"],
  ["industrial", "parts_washer", "Parts Washer", "percent", 15, "planning"],
  ["industrial", "scissor_vehicle_lift", "Scissor Vehicle Lift", "hours", 15000, "planning"],
  ["industrial", "truck_tyre_changer", "Truck & Tractor Tyre Changer", "hours", 15000, "planning"],
  ["industrial", "truck_wheel_balancer", "Truck Wheel Balancer", "hours", 15000, "planning"],
  ["industrial", "two_post_vehicle_lift", "Two-Post Vehicle Lift", "hours", 15000, "planning"],
  ["industrial", "vehicle_diagnostic_scanner", "Vehicle Diagnostic Scanner", "percent", 8, "planning"],
  ["industrial", "wheel_alignment_machine", "Wheel Alignment Machine", "hours", 15000, "planning"],
  ["industrial", "workshop_hydraulic_press", "Workshop Hydraulic Press", "percent", 15, "planning"],
  ["industrial", "blast_chiller_freezer", "Blast Chiller & Freezer", "hours", 20000, "planning"],
  ["industrial", "cube_ice_machine", "Cube Ice Machine", "hours", 20000, "planning"],
  ["industrial", "deli_slicer", "Deli Slicer", "hours", 20000, "planning"],
  ["industrial", "flake_ice_machine", "Flake Ice Machine", "hours", 20000, "planning"],
  ["industrial", "manual_sausage_filler", "Manual Sausage Filler", "percent", 15, "planning"],
  ["industrial", "meat_bandsaw", "Meat Band Saw", "hours", 20000, "planning"],
  ["industrial", "bowl_cutter", "Meat Bowl Cutter", "hours", 20000, "planning"],
  ["industrial", "brine_injector", "Meat Brine Injector", "hours", 20000, "planning"],
  ["industrial", "meat_mincer", "Meat Mincer", "hours", 20000, "planning"],
  ["industrial", "meat_mixer", "Meat Mixer", "hours", 20000, "planning"],
  ["industrial", "meat_smoking_chamber", "Meat Smoking & Cooking Chamber", "hours", 20000, "planning"],
  ["industrial", "meat_tumbler", "Meat Tumbler", "hours", 20000, "planning"],
  ["industrial", "powered_sausage_filler", "Powered Sausage Filler", "hours", 20000, "planning"],
  ["industrial", "bakery_deck_oven", "Bakery Deck Oven", "hours", 20000, "planning"],
  ["industrial", "bakery_prover", "Bakery Prover", "hours", 20000, "planning"],
  ["industrial", "bakery_rack_oven", "Bakery Rack Oven", "hours", 20000, "planning"],
  ["industrial", "bread_slicer", "Bread Slicer", "hours", 20000, "planning"],
  ["industrial", "dough_divider_rounder", "Dough Divider & Rounder", "hours", 20000, "planning"],
  ["industrial", "spiral_dough_mixer", "Dough Mixer", "hours", 20000, "planning"],
  ["industrial", "dough_moulder", "Dough Moulder", "hours", 20000, "planning"],
  ["industrial", "dough_rounder", "Dough Rounder", "hours", 20000, "planning"],
  ["industrial", "pastry_sheeter", "Pastry Sheeter", "hours", 20000, "planning"],
  ["industrial", "planetary_food_mixer", "Planetary Food Mixer", "hours", 20000, "planning"],
  ["industrial", "fabric_cutting_machine", "Fabric Cutting Machine", "percent", 15, "planning"],
  ["industrial", "industrial_coverstitch_machine", "Industrial Coverstitch Machine", "percent", 15, "planning"],
  ["industrial", "industrial_embroidery_machine", "Industrial Embroidery Machine", "percent", 15, "planning"],
  ["industrial", "industrial_overlocker", "Industrial Overlocker", "percent", 15, "planning"],
  ["industrial", "industrial_pattern_sewing_machine", "Industrial Pattern Sewing Machine", "percent", 15, "planning"],
  ["industrial", "industrial_lockstitch_machine", "Industrial Straight-Stitch Sewing Machine", "percent", 15, "planning"],
  ["industrial", "commercial_tumble_dryer", "Commercial Tumble Dryer", "percent", 15, "planning"],
  ["industrial", "commercial_washer_extractor", "Commercial Washing Machine", "percent", 15, "planning"],
  ["industrial", "dry_cleaning_machine", "Dry-Cleaning Machine", "percent", 15, "planning"],
  ["industrial", "garment_press", "Garment Press", "percent", 15, "planning"],
  ["industrial", "flatwork_ironer", "Laundry Roller Iron", "percent", 15, "planning"],
  ["industrial", "vacuum_ironing_table", "Vacuum Ironing Table", "percent", 15, "planning"],
  ["industrial", "booklet_maker", "Booklet Maker", "percent", 10, "planning"],
  ["industrial", "dtf_printer", "DTF Transfer Printer", "percent", 8, "planning"],
  ["industrial", "digital_cutting_table", "Digital Cutting Table", "percent", 10, "planning"],
  ["industrial", "digital_production_press", "Digital Production Printing Press", "percent", 8, "planning"],
  ["industrial", "paper_creaser", "Paper Creaser", "percent", 10, "planning"],
  ["industrial", "powered_paper_guillotine", "Powered Paper Guillotine", "percent", 10, "planning"],
  ["industrial", "roll_laminator", "Roll Laminator", "percent", 10, "planning"],
  ["industrial", "sheetfed_offset_press", "Sheetfed Offset Printing Press", "percent", 20, "planning"],
  ["industrial", "textile_printer", "Textile Printer", "percent", 8, "planning"],
  ["industrial", "transfer_heat_press", "Transfer Heat Press", "percent", 10, "planning"],
  ["industrial", "vinyl_cutter", "Vinyl Cutting Plotter", "percent", 10, "planning"],
  ["industrial", "wide_format_flatbed_printer", "Wide-Format Flatbed Printer", "percent", 8, "planning"],
  ["industrial", "wide_format_roll_printer", "Wide-Format Roll Printer", "percent", 8, "planning"],
  ["industrial", "extrusion_blow_moulder", "Plastic Blow Moulding Machine", "percent", 15, "planning"],
  ["industrial", "plastic_extruder", "Plastic Extruder", "hours", 40000, "planning"],
  ["industrial", "injection_moulding_machine", "Plastic Injection Moulding Machine", "percent", 15, "planning"],
  ["industrial", "belt_filter_press", "Belt Filter Press", "hours", 40000, "planning"],
  ["industrial", "decanter_centrifuge", "Decanter Centrifuge", "hours", 40000, "planning"],
  ["industrial", "drum_ibc_mixer", "Drum & IBC Mixer", "hours", 40000, "planning"],
  ["industrial", "filter_press", "Filter Press", "hours", 40000, "planning"],
  ["industrial", "high_shear_mixer", "High-Shear Mixer", "hours", 40000, "planning"],
  ["industrial", "high_speed_disperser", "Paint & Liquid Disperser", "hours", 40000, "planning"],
  ["industrial", "ribbon_blender", "Powder Ribbon Blender", "hours", 40000, "planning"],
  ["industrial", "tank_agitator", "Tank Agitator", "hours", 40000, "planning"],
  ["industrial", "concrete_block_machine", "Concrete Block & Paver Machine", "hours", 30000, "planning"],
  ["industrial", "earth_block_press", "Earth Block Press", "hours", 30000, "planning"],
  ["industrial", "mobile_asphalt_plant", "Mobile Asphalt Mixing Plant", "hours", 30000, "planning"],
  ["industrial", "mobile_concrete_batching_plant", "Mobile Concrete Batching Plant", "hours", 30000, "planning"],
  ["industrial", "stationary_asphalt_plant", "Stationary Asphalt Mixing Plant", "hours", 30000, "planning"],
  ["industrial", "stationary_concrete_batching_plant", "Stationary Concrete Batching Plant", "hours", 30000, "planning"],
  ["motor", "hatchback", "Hatchback", "km", 300000, "existing"],
  ["motor", "sedan_fastback", "Sedan & Fastback", "km", 300000, "existing"],
  ["motor", "coupe", "Coupe", "km", 300000, "existing"],
  ["motor", "convertible", "Convertible", "km", 300000, "existing"],
  ["motor", "station_wagon", "Station Wagon", "km", 300000, "existing"],
  ["motor", "suv_crossover", "SUV & Crossover", "km", 300000, "existing"],
  ["motor", "mpv_people_carrier", "MPV & People Carrier", "km", 300000, "existing"],
  ["motor", "single_cab_bakkie", "Single Cab Bakkie", "km", 350000, "existing"],
  ["motor", "extended_cab_bakkie", "Extended Cab Bakkie", "km", 350000, "existing"],
  ["motor", "double_cab_bakkie", "Double Cab Bakkie", "km", 350000, "existing"],
  ["motor", "compact_panel_van", "Compact Panel Van", "km", 350000, "existing"],
  ["motor", "panel_van", "Panel Van", "km", 450000, "existing"],
  ["motor", "crew_van", "Crew Van", "km", 450000, "existing"],
  ["motor", "minibus", "Minibus", "km", 350000, "existing"],
  ["motor", "midibus", "Midibus", "km", 600000, "planning"],
  ["motor", "commuter_bus", "Commuter Bus", "km", 900000, "existing"],
  ["motor", "city_bus", "City Bus", "km", 900000, "existing"],
  ["motor", "coach", "Coach", "km", 900000, "existing"],
  ["motor", "double_decker_coach", "Double-Decker Coach", "km", 900000, "existing"],
  ["motor", "articulated_bus", "Articulated Bus", "km", 900000, "existing"],
  ["motor", "bi_articulated_bus", "Bi-Articulated Bus", "km", 900000, "existing"],
  ["motor", "double_decker_city_bus", "Double-Decker City Bus", "km", 900000, "existing"],
  ["motor", "truck_tractor", "Truck Tractor", "km", 800000, "existing"],
  ["motor", "truck_chassis_cab", "Truck Chassis Cab", "km", 800000, "existing"],
  ["motor", "flatbed_truck", "Flatbed Truck", "km", 800000, "existing"],
  ["motor", "dropside_truck", "Dropside Truck", "km", 800000, "existing"],
  ["motor", "box_truck", "Box Truck", "km", 800000, "existing"],
  ["motor", "curtainside_truck", "Curtainside Truck", "km", 800000, "existing"],
  ["motor", "refrigerated_truck", "Refrigerated Truck", "km", 800000, "existing"],
  ["motor", "tipper_truck", "Tipper Truck", "km", 800000, "existing"],
  ["motor", "grain_truck", "Grain Truck", "km", 800000, "existing"],
  ["motor", "livestock_truck", "Livestock Truck", "km", 800000, "existing"],
  ["motor", "timber_truck", "Timber Truck", "km", 800000, "existing"],
  ["motor", "sugar_cane_truck", "Sugar Cane Truck", "km", 800000, "existing"],
  ["motor", "crane_delivery_truck", "Crane Delivery Truck", "km", 800000, "existing"],
  ["motor", "beavertail_truck", "Beavertail Truck", "km", 800000, "existing"],
  ["motor", "rollback_truck", "Rollback Truck", "km", 800000, "existing"],
  ["motor", "wheel_lift_tow_truck", "Wheel-Lift Tow Truck", "km", 800000, "existing"],
  ["motor", "heavy_recovery_truck", "Heavy Recovery Truck", "km", 800000, "existing"],
  ["motor", "water_tanker_truck", "Water Tanker Truck", "km", 800000, "existing"],
  ["motor", "fuel_tanker_truck", "Fuel Tanker Truck", "km", 800000, "existing"],
  ["motor", "food_liquid_tanker_truck", "Food Liquid Tanker Truck", "km", 800000, "existing"],
  ["motor", "chemical_tanker_truck", "Chemical Tanker Truck", "km", 800000, "existing"],
  ["motor", "rear_loader_refuse_truck", "Rear-Loader Refuse Truck", "km", 600000, "planning"],
  ["motor", "front_loader_refuse_truck", "Front-Loader Refuse Truck", "km", 600000, "planning"],
  ["motor", "skip_loader_truck", "Skip Loader Truck", "km", 600000, "planning"],
  ["motor", "hooklift_truck", "Hooklift Truck", "km", 600000, "planning"],
  ["motor", "vacuum_tanker_truck", "Vacuum Tanker Truck", "km", 600000, "planning"],
  ["motor", "industrial_vacuum_truck", "Industrial Vacuum Truck", "km", 600000, "planning"],
  ["motor", "jetting_truck", "Drain Jetting Truck", "km", 600000, "planning"],
  ["motor", "combination_jet_vac_truck", "Combination Jet & Vacuum Truck", "km", 600000, "planning"],
  ["motor", "truck_street_sweeper", "Truck-Mounted Street Sweeper", "km", 600000, "planning"],
  ["motor", "compact_street_sweeper", "Compact Street Sweeper", "hours", 10000, "planning"],
  ["motor", "street_washing_truck", "Street Washing Truck", "km", 600000, "planning"],
  ["motor", "concrete_mixer_truck", "Concrete Mixer Truck", "km", 600000, "planning"],
  ["motor", "truck_aerial_platform", "Truck-Mounted Aerial Platform", "km", 600000, "planning"],
  ["motor", "service_truck", "Service Truck", "km", 600000, "planning"],
  ["motor", "fire_engine", "Fire Engine", "km", 400000, "planning"],
  ["motor", "fire_water_tanker", "Fire Water Tanker", "km", 400000, "planning"],
  ["motor", "bush_fire_vehicle", "Bush Fire Vehicle", "km", 400000, "planning"],
  ["motor", "airport_fire_vehicle", "Airport Fire Vehicle", "hours", 10000, "planning"],
  ["motor", "aerial_fire_appliance", "Aerial Fire Appliance", "km", 400000, "planning"],
  ["motor", "refrigerated_van", "Refrigerated Van", "km", 450000, "existing"],
  ["motor", "ambulance", "Ambulance", "km", 450000, "existing"],
  ["motor", "hearse", "Hearse", "km", 450000, "existing"],
  ["motor", "food_truck", "Food Truck", "km", 450000, "existing"],
  ["motor", "heavy_flatdeck_trailer", "Flatdeck Freight Trailer", "percent", 25, "planning"],
  ["motor", "heavy_dropside_trailer", "Dropside Freight Trailer", "percent", 25, "planning"],
  ["motor", "tautliner_trailer", "Tautliner Trailer", "percent", 25, "planning"],
  ["motor", "dry_freight_trailer", "Box Freight Trailer", "percent", 25, "planning"],
  ["motor", "refrigerated_freight_trailer", "Refrigerated Freight Trailer", "percent", 25, "planning"],
  ["motor", "stepdeck_trailer", "Stepdeck Trailer", "percent", 25, "planning"],
  ["motor", "lowbed_trailer", "Lowbed Trailer", "percent", 25, "planning"],
  ["motor", "skeletal_container_trailer", "Container Trailer", "percent", 25, "planning"],
  ["motor", "container_sidelifter_trailer", "Container Sidelifter Trailer", "percent", 25, "planning"],
  ["motor", "multi_car_carrier_trailer", "Multi-car Carrier Trailer", "percent", 25, "planning"],
  ["motor", "truck_carrier_trailer", "Truck Carrier Trailer", "percent", 25, "planning"],
  ["motor", "heavy_livestock_trailer", "Livestock Freight Trailer", "percent", 25, "planning"],
  ["motor", "poultry_carrier_trailer", "Poultry Carrier Trailer", "percent", 25, "planning"],
  ["motor", "timber_trailer", "Timber Trailer", "percent", 25, "planning"],
  ["motor", "sugarcane_trailer", "Sugarcane Road Trailer", "percent", 25, "planning"],
  ["motor", "converter_dolly", "Trailer Dolly", "percent", 25, "planning"],
  ["motor", "side_tipper_trailer", "Side Tipper Trailer", "percent", 25, "planning"],
  ["motor", "dropside_tipper_trailer", "Dropside Tipper Trailer", "percent", 25, "planning"],
  ["motor", "end_tipper_trailer", "End Tipper Trailer", "percent", 25, "planning"],
  ["motor", "bottom_dump_trailer", "Bottom Dump Trailer", "percent", 25, "planning"],
  ["motor", "moving_floor_trailer", "Moving Floor Trailer", "percent", 25, "planning"],
  ["motor", "fuel_tanker_trailer", "Fuel Tanker Trailer", "percent", 25, "planning"],
  ["motor", "food_liquid_tanker_trailer", "Food-grade Tanker Trailer", "percent", 25, "planning"],
  ["motor", "chemical_tanker_trailer", "Chemical Tanker Trailer", "percent", 25, "planning"],
  ["motor", "heated_liquid_tanker_trailer", "Heated Liquid Tanker Trailer", "percent", 25, "planning"],
  ["motor", "lpg_tanker_trailer", "LPG Tanker Trailer", "percent", 25, "planning"],
  ["motor", "dry_bulk_tanker_trailer", "Dry Bulk Tanker Trailer", "percent", 25, "planning"],
  ["motor", "auger_bulk_trailer", "Auger Bulk Trailer", "percent", 25, "planning"],
  ["motor", "vacuum_tanker_trailer", "Vacuum Tanker Trailer", "percent", 25, "planning"],
  ["motor", "luggage_trailer", "Luggage Trailer", "percent", 20, "planning"],
  ["motor", "utility_trailer", "Open Utility Trailer", "percent", 20, "planning"],
  ["motor", "light_flatdeck_trailer", "Light Flatdeck Trailer", "percent", 20, "planning"],
  ["motor", "enclosed_cargo_trailer", "Enclosed Cargo Trailer", "percent", 20, "planning"],
  ["motor", "car_transporter_trailer", "Car Transporter Trailer", "percent", 20, "planning"],
  ["motor", "motorcycle_trailer", "Motorcycle Trailer", "percent", 20, "planning"],
  ["motor", "boat_trailer", "Boat Trailer", "percent", 20, "planning"],
  ["motor", "horsebox_trailer", "Horsebox Trailer", "percent", 20, "planning"],
  ["motor", "light_livestock_trailer", "Light Livestock Trailer", "percent", 20, "planning"],
  ["motor", "game_trailer", "Game Trailer", "percent", 20, "planning"],
  ["motor", "plant_transport_trailer", "Plant Transport Trailer", "percent", 20, "planning"],
  ["motor", "car_tow_dolly", "Car Tow Dolly", "percent", 20, "planning"],
  ["motor", "water_bowser_trailer", "Water Bowser Trailer", "percent", 20, "planning"],
  ["motor", "fuel_bowser_trailer", "Fuel Bowser Trailer", "percent", 20, "planning"],
  ["motor", "cable_drum_trailer", "Cable Drum Trailer", "percent", 20, "planning"],
  ["motor", "food_trailer", "Food Trailer", "percent", 20, "planning"],
  ["motor", "coldroom_trailer", "Coldroom Trailer", "percent", 20, "planning"],
  ["motor", "toilet_trailer", "Toilet Trailer", "percent", 20, "planning"],
  ["motor", "shower_trailer", "Shower Trailer", "percent", 20, "planning"],
  ["motor", "touring_caravan", "Touring Caravan", "percent", 25, "planning"],
  ["motor", "gravel_road_caravan", "Gravel Road Caravan", "percent", 25, "planning"],
  ["motor", "off_road_caravan", "Off-road Caravan", "percent", 25, "planning"],
  ["motor", "camping_trailer", "Camping Trailer", "percent", 25, "planning"],
  ["motor", "teardrop_camper", "Teardrop Camper", "percent", 25, "planning"],
  ["motor", "road_motorcycle", "Road Motorcycle", "km", 100000, "planning"],
  ["motor", "sports_motorcycle", "Sports Motorcycle", "km", 100000, "planning"],
  ["motor", "cruiser_motorcycle", "Cruiser Motorcycle", "km", 100000, "planning"],
  ["motor", "touring_motorcycle", "Touring Motorcycle", "km", 100000, "planning"],
  ["motor", "adventure_dual_purpose_motorcycle", "Adventure & Dual-Purpose Motorcycle", "km", 100000, "planning"],
  ["motor", "motor_scooter", "Scooter", "km", 100000, "planning"],
  ["motor", "motocross_motorcycle", "Motocross Bike", "hours", 1000, "planning"],
  ["motor", "enduro_motorcycle", "Enduro Bike", "hours", 2000, "planning"],
  ["motor", "youth_motorcycle", "Youth Motorcycle", "hours", 1000, "planning"],
  ["motor", "utility_quad", "Utility Quad Bike", "hours", 3000, "planning"],
  ["motor", "sport_quad", "Sport Quad Bike", "hours", 3000, "planning"],
  ["motor", "youth_quad", "Youth Quad Bike", "hours", 1500, "planning"],
  ["motor", "utility_side_by_side", "Utility Side-by-Side", "hours", 3000, "planning"],
  ["motor", "sport_side_by_side", "Sport Side-by-Side", "hours", 3000, "planning"],
  ["motor", "youth_side_by_side", "Youth Side-by-Side", "hours", 1500, "planning"],
  ["motor", "road_trike", "Road Trike", "km", 150000, "planning"],
  ["motor", "golf_cart", "Golf & Estate Cart", "hours", 8000, "planning"],
  ["motor", "passenger_shuttle_cart", "Passenger Shuttle Cart", "hours", 8000, "planning"],
  ["motor", "utility_cargo_cart", "Utility Cargo Cart", "hours", 8000, "planning"],
  ["motor", "passenger_tuk_tuk", "Passenger Tuk-Tuk", "km", 150000, "planning"],
  ["motor", "cargo_three_wheeler", "Cargo Three-Wheeler", "km", 150000, "planning"],
  ["motor", "campervan", "Campervan", "km", 400000, "planning"],
  ["motor", "motorhome", "Motorhome", "km", 400000, "planning"],
  ["motor", "expedition_motorhome", "Off-road Motorhome", "km", 400000, "planning"],
  ["motor", "game_viewer", "Game Viewer", "km", 350000, "planning"],
];

const profiles = new Map(BASIC_USAGE_FAMILIES.map(([sectorKey, familyKey, , primaryMetric, expectedLifetime, basis]) => [
  `${sectorKey}/${familyKey}`,
  Object.freeze({ version: BASIC_USAGE_PROFILE_VERSION, sectorKey, familyKey, primaryMetric, expectedLifetime,
    lifetimeUnit: primaryMetric === 'percent' ? 'years' as const : primaryMetric,
    confidence: basis === 'toyota' ? 'medium' as const : 'low' as const,
    basis, percentageFallback: true as const }),
]));

export function getBasicUsageProfile(sectorKey: string, familyKey: string): BasicUsageProfile {
  const profile = profiles.get(`${sectorKey}/${familyKey}`);
  if (!profile) throw new Error('Basic usage profile not found for this family.');
  return profile;
}

/** A reference life is an economic planning assumption, not a retirement deadline. */
export function basicLifetimeLabel(profile: BasicUsageProfile): string {
  return `${profile.expectedLifetime.toLocaleString('en-ZA')} ${profile.lifetimeUnit}`;
}
