import { AIM4PRICE_EMAIL_FONT_STACK, AIM4PRICE_EMAIL_LOGO_PATH, buildEmailBrandHeader } from './email-brand';
import { billingEscape as escape } from './billing-report';
import { billingDate, money, type BillingCustomer } from './billing-shared';

type EmailInvoice = { number: string; customer: BillingCustomer; totalCents: number; paidCents: number; dueDate: string; issuer: { email: string; bank: string; accountNumber: string; accountName?: string; branchCode?: string } };
/** Inline styles and presentation tables keep the invoice readable in email clients. */
export function buildBillingEmail(invoice: EmailInvoice, url: string) {
 const {number,customer,issuer}=invoice;
 const balance=money(invoice.totalCents-invoice.paidCents);
 const detail=(label:string,value:string)=>`<tr><td style="padding:9px 0;color:#64786f;font-size:13px">${escape(label)}</td><td align="right" style="padding:9px 0 9px 16px;font-size:14px;font-weight:bold;overflow-wrap:anywhere">${escape(value)}</td></tr>`;
 return {text:`Hi ${customer.name},\n\nYour Aim4price.com invoice ${number} is attached.\nInvoice total: ${money(invoice.totalCents)}\nRecorded payments: ${money(invoice.paidCents)}\nBalance: ${balance}\nDue: ${billingDate(invoice.dueDate)}\nNo VAT applicable.\n\nBank: ${issuer.bank}\nAccount: ${issuer.accountNumber}\nReference: ${number}\n\nSign in to view your invoice and current payment status: ${url}\n\nPayments appear after verification. For help, contact ${issuer.email}.\n\nAim4price.com\nAsset Intelligence & Management.`,html:`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"></head><body style="margin:0;padding:0;background:#f2f6f3;color:#173c32;font-family:${AIM4PRICE_EMAIL_FONT_STACK}"><div style="display:none;max-height:0;overflow:hidden">Invoice ${escape(number)} · ${escape(balance)} balance · Due ${escape(billingDate(invoice.dueDate))}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#ffffff;border:1px solid #d7e5dc;border-radius:12px;overflow:hidden">
 ${buildEmailBrandHeader(new URL(AIM4PRICE_EMAIL_LOGO_PATH,url).toString())}
 <tr><td style="padding:30px"><div style="font-size:12px;color:#667f72;letter-spacing:1px;text-transform:uppercase">Your invoice</div><h1 style="font-size:25px;font-weight:bold;line-height:1.3;margin:9px 0 22px">${escape(number)}</h1><p style="font-size:15px;line-height:1.7;margin:0 0 22px">Hi ${escape(customer.name)},<br>Your invoice is ready. A PDF copy is attached for your records.</p>
 <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#edf5f0;border:1px solid #d2e4d9;border-radius:8px"><tr><td style="padding:22px"><div style="font-size:12px;color:#587465">${invoice.paidCents>=invoice.totalCents?'Paid in full':'Balance to pay'}</div><div style="font-size:32px;font-weight:bold;line-height:1.3;margin:7px 0">${escape(balance)}</div><div style="font-size:13px;color:#587465">Due ${escape(billingDate(invoice.dueDate))}</div></td></tr></table>
 <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:16px">${detail('Invoice total',money(invoice.totalCents))}${invoice.paidCents?detail('Recorded payments',money(invoice.paidCents)):''}${customer.businessName?detail('Business',customer.businessName):''}${customer.reference?detail('Your reference',customer.reference):''}</table><p style="font-size:12px;color:#708277;margin:8px 0 25px">No VAT applicable.</p>
 <h2 style="font-size:16px;margin:0 0 8px">Payment details</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #e0e9e3">${detail('Bank',issuer.bank)}${issuer.accountName?detail('Account name',issuer.accountName):''}${detail('Account number',issuer.accountNumber)}${issuer.branchCode?detail('Branch code',issuer.branchCode):''}${detail('Payment reference',number)}</table>
 <p style="font-size:13px;line-height:1.7;color:#64786f;margin:15px 0 24px">Use your invoice number as the payment reference. Payments appear in your account after Aim4price verifies receipt.</p>
 <table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="border-radius:6px;background:#1a654d"><a href="${escape(url)}" style="display:inline-block;padding:15px 24px;color:#ffffff;text-decoration:none;font-size:14px;font-weight:bold">View invoice</a></td></tr></table><p style="font-size:12px;color:#708277;line-height:1.6;margin:12px 0 0">Sign in to view your invoice and current payment status.</p></td></tr>
 <tr><td style="padding:20px 30px;border-top:1px solid #e0e9e3;background:#fafcfb;font-size:13px;line-height:1.7;color:#64786f">Questions about this invoice? <a href="mailto:${escape(encodeURIComponent(issuer.email))}" style="color:#1a654d">${escape(issuer.email)}</a></td></tr></table></td></tr></table></body></html>`};
}
