import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { REPORT_THEME_CSS } from './report-theme';
import { BILLING_ISSUER, money, type BillingInvoice } from './billing-shared';
export function billingEscape(value: unknown): string { return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)); }
let assets: Promise<{font:string;logo:string}> | undefined;
async function reportAssets() {
  if(!assets)assets=Promise.all([readFile(path.join(process.cwd(),'public/field-manager/montserrat-latin.woff')),readFile(path.join(process.cwd(),'public/brand/aim4price-mark-black.png'))]).then(([font,logo])=>({font:font.toString('base64'),logo:logo.toString('base64')})).catch(e=>{assets=undefined;throw e;});
  return assets;
}
export async function buildBillingInvoiceHtml(invoice: BillingInvoice, issuer: Record<string,string> = BILLING_ISSUER): Promise<string> {
  const {font,logo}=await reportAssets(),e=billingEscape;
  const issued=invoice.issuedAt ? new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',day:'2-digit',month:'short',year:'numeric'}).format(new Date(invoice.issuedAt)) : 'Not issued';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(invoice.number || 'Draft invoice')} - Aim4price</title><style>
  @font-face{font-family:Montserrat;src:url(data:font/woff;base64,${font}) format('woff');font-weight:100 900;font-display:block}
  *{box-sizing:border-box} @page{size:A4;margin:12mm 10mm 15mm} body{margin:0;font:10px/1.5 Montserrat,Arial,sans-serif;color:#173c32;background:#edf4f0}
  .assetReportPage{max-width:190mm;margin:20px auto;padding:7mm;background:white}.assetReportHeader{display:grid;grid-template-columns:48px 1fr 160px;gap:12px;align-items:center;border-bottom:1px solid #b9d0c5;padding-bottom:14px}.assetReportLogo{width:44px;max-height:44px;object-fit:contain}.assetReportDocumentTitle strong{display:block;font-size:19px}.assetReportDocumentTitle span{color:#60756d}.meta{text-align:right;font-size:9px}.meta strong{display:block}
  .assetReportOverview{display:grid;grid-template-columns:1.5fr 1fr;border:1px solid #b9d0c5;margin:16px 0;break-inside:avoid}.assetReportIdentity,.assetReportValuationCard{padding:16px}.assetReportKicker{font-size:9px;margin:0 0 7px;text-transform:uppercase}.assetReportTitle{font-size:23px;margin:0 0 7px}.assetReportMeta{margin:0}.assetReportValuationCard h2{font-size:10px;margin:0 0 8px}.assetReportValue{display:block;font-size:25px}.assetReportVat{display:block;margin-top:8px;font-size:9px}
  .parties{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:18px 0}.assetReportSection{border:1px solid #b9d0c5;padding:12px;break-inside:avoid}.assetReportSection h2{font-size:11px;margin:0 0 9px}.address{white-space:pre-line;overflow-wrap:anywhere}.address strong{display:block}.assetReportTable{width:100%;border-collapse:collapse;table-layout:fixed;font-size:10px}.assetReportTable th,.assetReportTable td{padding:10px 8px;text-align:left;border-bottom:1px solid #d6e4dd;vertical-align:top}.assetReportTable th:nth-child(n+2),.assetReportTable td:nth-child(n+2){text-align:right}.assetReportTable th:first-child{width:52%}.assetReportTable th:nth-child(2){width:10%}.assetReportTable th:nth-child(3),.assetReportTable th:nth-child(4){width:19%}thead{display:table-header-group}tr{break-inside:avoid}.totals{margin:14px 0 18px auto;width:48%;border-top:2px solid #197454;break-inside:avoid}.totalRow{display:flex;justify-content:space-between;gap:12px;padding:8px}.grand{background:#eaf5ef;font-size:14px;font-weight:700}.payment{display:grid;grid-template-columns:1fr 1fr;gap:16px;break-inside:avoid}.payment p{margin:3px 0}.note{white-space:pre-wrap;overflow-wrap:anywhere;margin-top:15px;break-inside:avoid}.footer{margin-top:25px;border-top:1px solid #d6e4dd;padding-top:10px;color:#60756d;font-size:9px}.draft{font-weight:700;color:#8f3f26}
  ${REPORT_THEME_CSS}
  @media print{html,body{background:white}.assetReportPage{margin:0;padding:0;max-width:none;box-shadow:none;border-radius:0}}
  </style></head><body><main class="assetReportPage"><header class="assetReportHeader"><img class="assetReportLogo" src="data:image/png;base64,${logo}" alt="Aim4price"><div class="assetReportDocumentTitle"><strong>Aim4price Invoice</strong><span>Account services</span></div><div class="meta"><strong>${e(invoice.number || 'DRAFT - NOT ISSUED')}</strong><span>Issued ${e(issued)}</span></div></header>
  <section class="assetReportOverview"><div class="assetReportIdentity"><p class="assetReportKicker">${invoice.status==='draft'?'Draft for review':'Invoice'}</p><h1 class="assetReportTitle">${e(invoice.customer.name)}</h1><p class="assetReportMeta">Payment due ${e(invoice.dueDate)}</p>${invoice.status==='draft'?'<p class="draft">Draft only. Do not pay until issued.</p>':''}</div><aside class="assetReportValuationCard"><h2>Invoice total</h2><strong class="assetReportValue">${e(money(invoice.totalCents))}</strong><span class="assetReportVat">${e(issuer.vat)}</span></aside></section>
  <div class="parties"><section class="assetReportSection"><h2>From</h2><div class="address"><strong>${e(issuer.name)}</strong>${e(issuer.address)}<br>${e(issuer.email)}</div></section><section class="assetReportSection"><h2>Bill to</h2><div class="address"><strong>${e(invoice.customer.name)}</strong>${e(invoice.customer.address)}<br>${e(invoice.customer.email)}</div></section></div>
  <table class="assetReportTable"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${invoice.lines.map(line=>`<tr><td>${e(line.description)}</td><td>${line.quantity}</td><td>${e(money(line.unitCents))}</td><td>${e(money(line.totalCents))}</td></tr>`).join('')}</tbody></table>
  <div class="totals"><div class="totalRow"><span>Subtotal</span><strong>${e(money(invoice.totalCents))}</strong></div><div class="totalRow"><span>VAT</span><span>Not applicable</span></div><div class="totalRow grand"><span>Total (ZAR)</span><strong>${e(money(invoice.totalCents))}</strong></div></div>
  <div class="payment"><section class="assetReportSection"><h2>Payment details</h2><p><strong>Bank:</strong> ${e(issuer.bank)}</p><p><strong>Account number:</strong> ${e(issuer.accountNumber)}</p><p><strong>Reference:</strong> ${e(invoice.number || 'Available when issued')}</p></section><section class="assetReportSection"><h2>Questions about this invoice?</h2><p>${e(issuer.email)}</p><p>Please use the invoice number as your payment reference. Payment is recorded after verification.</p></section></div>${invoice.note?`<div class="note">${e(invoice.note)}</div>`:''}<footer class="footer">Aim4price · Know what you have. Know what it’s worth. Know what it costs.<br>This invoice records the original charge. View current payments and balance in your Aim4price billing account.</footer></main></body></html>`;
}
