const brandNames = [
  'Zoomlion',
  'YTO',
  'Yanmar',
  'VST',
  'Versatile',
  'Van Breda',
  'Valtra',
  'Ursus',
  'Tafe',
  'Sonalika',
  'Same',
  'Renault',
  'New Holland',
  'Minneapolis-Moline',
  'Mercedes',
  'Massey Ferguson',
  'McCormick',
  'Mahindra',
  'Lovol',
  'Leyland',
  'Landini',
  'Lamborghini',
  'Kubota',
  'John Deere',
  'Kirovets',
  'Jinma',
  'JCB',
  'J.I. Case',
  'International Harvester',
  'Hinomoto',
  'Foton',
  'Fordson Major',
  'Ford',
  'Ford New Holland',
  'Fiat',
  'Fendt',
  'Deutz-Fahr',
  'Farmtrac',
  'Deutz',
  'David Brown',
  'County',
  'Claas',
  'Challenger',
  'Case IH',
  'Buhler Versatile',
  'Belarus',
  'Allis Chalmers',
  'ACO',
  'Agrico',
  'Antonio Carraro',
];

export const brands = brandNames.map((name) => ({
  name,
  slug: name
    .toLowerCase()
    .replace(/\./g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, ''),
}));
