-- Admin-only retainer work tracker.
-- Stores explicit work sessions and aggregate friendly page totals only.
-- Raw URLs, clicks, field values and owner-facing access events are intentionally excluded.

begin;

create table if not exists public.admin_work_sessions (
  id text primary key,
  admin_user_id text not null,
  client_user_id text not null,
  client_name text not null default '',
  client_email text not null default '',
  client_account_type text not null default '',
  started_at timestamptz not null default now(),
  stopped_at timestamptz,
  last_heartbeat_at timestamptz not null default now(),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  current_page_key text not null default 'admin-users',
  current_page_label text not null default 'Admin - User Accounts',
  tracking_active boolean not null default true,
  note text not null default '',
  include_in_report boolean not null default true,
  show_times_in_report boolean not null default false,
  show_note_in_report boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (stopped_at is null or stopped_at >= started_at)
);

create unique index if not exists idx_admin_work_sessions_one_active_per_admin
  on public.admin_work_sessions(admin_user_id)
  where stopped_at is null;

create index if not exists idx_admin_work_sessions_admin_started
  on public.admin_work_sessions(admin_user_id, started_at desc);

create index if not exists idx_admin_work_sessions_client_started
  on public.admin_work_sessions(client_user_id, started_at desc);

create table if not exists public.admin_work_page_totals (
  session_id text not null references public.admin_work_sessions(id) on delete cascade,
  work_date date not null,
  page_key text not null,
  page_label text not null,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (session_id, work_date, page_key)
);

create index if not exists idx_admin_work_page_totals_work_date
  on public.admin_work_page_totals(work_date, session_id);

comment on table public.admin_work_sessions is
  'Admin-only explicit retainer work sessions. Owners receive only reports manually generated by Admin.';

comment on table public.admin_work_page_totals is
  'Aggregate friendly page-level time. Never stores raw paths, entity IDs, clicks or form values.';

commit;
